import React,{useEffect,useMemo,useRef,useState}from'react';
import{createRoot}from'react-dom/client';
import{Canvas,useFrame,useThree}from'@react-three/fiber';
import*as THREE from'three';
import{OrbitControls as ThreeOrbitControls}from'three/examples/jsm/controls/OrbitControls.js';
import{STLExporter}from'three/examples/jsm/exporters/STLExporter.js';
import{RoundedBoxGeometry}from'three/examples/jsm/geometries/RoundedBoxGeometry.js';
import{Brush,Evaluator,ADDITION,SUBTRACTION}from'three-bvh-csg';
import'./styles.css';

const evaluator=new Evaluator();evaluator.attributes=['position','normal'];
const units={
'1U':{w:19.40,d:19.40},'1.25U':{w:24.15,d:19.40},'1.5U':{w:28.90,d:19.40},'1.75U':{w:33.65,d:19.40},'2U':{w:38.40,d:19.40},'2.25U':{w:43.15,d:19.40},'2.75U':{w:52.70,d:19.40},'6.25U':{w:119.20,d:19.40}
};
const fitPreset={Tight:-0.15,Normal:0,Loose:0.20};
const keyProfiles={Cherry:{height:9.5,top:13.2,dish:.65,tilt:-6},OEM:{height:11.2,top:13.5,dish:.75,tilt:-7},XDA:{height:9.1,top:14.2,dish:.35,tilt:0},DSA:{height:7.6,top:14,dish:.45,tilt:0},SA:{height:13.5,top:12.7,dish:1,tilt:-8}};

function brush(g){const b=new Brush(g);b.updateMatrixWorld(true);return b}
function csg(a,b,op){a.updateMatrixWorld(true);b.updateMatrixWorld(true);const out=evaluator.evaluate(a,b,op);out.geometry.computeVertexNormals();return out}
function roundedBox(w,d,h,r=2){const g=new RoundedBoxGeometry(w,h,d,4,Math.max(.2,Math.min(r,w/2-.05,d/2-.05,h/2-.05)));g.rotateX(Math.PI/2);return g}
function frustumBox(bottomW,bottomD,topW,topD,h){const z0=0,z1=h,verts=[[-bottomW/2,-bottomD/2,z0],[bottomW/2,-bottomD/2,z0],[bottomW/2,bottomD/2,z0],[-bottomW/2,bottomD/2,z0],[-topW/2,-topD/2,z1],[topW/2,-topD/2,z1],[topW/2,topD/2,z1],[-topW/2,topD/2,z1]],pos=verts.flat(),idx=[0,2,1,0,3,2,4,5,6,4,6,7,0,1,5,0,5,4,1,2,6,1,6,5,2,3,7,2,7,6,3,0,4,3,4,7];const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));g.setIndex(idx);g.computeVertexNormals();return g}
function crossPeg(total,arm,height,x,y,z){const g1=new THREE.BoxGeometry(total,arm,height),g2=new THREE.BoxGeometry(arm,total,height);g1.translate(x,y,z+height/2);g2.translate(x,y,z+height/2);return csg(brush(g1),brush(g2),ADDITION)}

function buildTray(t){
 const enabled=t.cells.filter(c=>c.enabled);const maxOpenW=Math.max(...enabled.map(c=>(units[c.unit]?.w||c.customW)+t.globalClearance*2+c.fitOffset),19.4);const maxOpenD=Math.max(...enabled.map(c=>(units[c.unit]?.d||c.customD)+t.globalClearance*2+c.fitOffset),19.4);
 const W=(t.cols-1)*t.pitchX+maxOpenW+t.edge*2,D=(t.rows-1)*t.pitchY+maxOpenD+t.edge*2;
 if(t.mode==='Pocket'){
  const H=t.baseThickness+t.pocketDepth+t.topLip;const outer=roundedBox(W,D,H,t.outerRadius);outer.translate(0,0,H/2);let solid=brush(outer);
  t.cells.forEach((cell,i)=>{if(!cell.enabled)return;const r=Math.floor(i/t.cols),c=i%t.cols,x=(c-(t.cols-1)/2)*t.pitchX,y=((t.rows-1)/2-r)*t.pitchY,base=units[cell.unit]||{w:cell.customW,d:cell.customD},openW=base.w+t.globalClearance*2+cell.fitOffset,openD=base.d+t.globalClearance*2+cell.fitOffset,bottomW=Math.max(4,openW-t.taperDelta),bottomD=Math.max(4,openD-t.taperDelta),pocketH=t.pocketDepth+t.topLip+.8;const p=frustumBox(bottomW,bottomD,openW,openD,pocketH);p.translate(x,y,t.baseThickness-.15);solid=csg(solid,brush(p),SUBTRACTION);
    if(t.fingerNotch){const n=new THREE.CylinderGeometry(t.notchRadius,t.notchRadius,t.pocketDepth+2,32);n.rotateX(Math.PI/2);n.translate(x,y-openD/2+t.notchRadius*.45,t.baseThickness+t.pocketDepth*.55);solid=csg(solid,brush(n),SUBTRACTION)}
  });
  const g=solid.geometry.clone();g.rotateX(-Math.PI/2);g.computeVertexNormals();return{geometry:g,W,D,H};
 }
 const H=t.mountPlate+t.pegHeight;const plate=roundedBox(W,D,t.mountPlate,t.outerRadius);plate.translate(0,0,t.mountPlate/2);let solid=brush(plate);
 t.cells.forEach((cell,i)=>{if(!cell.enabled)return;const r=Math.floor(i/t.cols),c=i%t.cols,x=(c-(t.cols-1)/2)*t.pitchX,y=((t.rows-1)/2-r)*t.pitchY,fit=cell.fitOffset,pegTotal=Math.max(3.6,t.pegTotal+fit),pegArm=Math.max(.85,t.pegArm+fit*.45);solid=csg(solid,crossPeg(pegTotal,pegArm,t.pegHeight,x,y,t.mountPlate-.05),ADDITION);if(t.supportRing){const ringOuter=new THREE.CylinderGeometry(t.ringOuter/2,t.ringOuter/2,t.ringHeight,36),ringInner=new THREE.CylinderGeometry(t.ringInner/2,t.ringInner/2,t.ringHeight+1,36);ringOuter.rotateX(Math.PI/2);ringInner.rotateX(Math.PI/2);ringOuter.translate(x,y,t.mountPlate+t.ringHeight/2);ringInner.translate(x,y,t.mountPlate+t.ringHeight/2);solid=csg(solid,csg(brush(ringOuter),brush(ringInner),SUBTRACTION),ADDITION)}});
 const g=solid.geometry.clone();g.rotateX(-Math.PI/2);g.computeVertexNormals();return{geometry:g,W,D,H};
}

function keycapLoft(bw,bd,tw,td,h){const levels=6,sides=32,pos=[],idx=[],rings=[];for(let l=0;l<=levels;l++){const t=l/levels,w=THREE.MathUtils.lerp(bw,tw,t),d=THREE.MathUtils.lerp(bd,td,t),start=pos.length/3;for(let i=0;i<sides;i++){const a=i/sides*Math.PI*2;pos.push(Math.cos(a)*w/2,Math.sin(a)*d/2,t*h)}rings.push(start)}for(let l=0;l<levels;l++)for(let i=0;i<sides;i++){const a=rings[l]+i,b=rings[l]+(i+1)%sides,c=rings[l+1]+(i+1)%sides,d=rings[l+1]+i;idx.push(a,b,c,a,c,d)}const tc=pos.length/3;pos.push(0,0,h);for(let i=0;i<sides;i++)idx.push(rings[levels]+i,rings[levels]+(i+1)%sides,tc);const bc=pos.length/3;pos.push(0,0,0);for(let i=0;i<sides;i++)idx.push(rings[0]+(i+1)%sides,rings[0]+i,bc);const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));g.setIndex(idx);g.computeVertexNormals();return g}
function buildKeycap(k){let solid=brush(keycapLoft(k.width,k.depth,k.topWidth,k.topDepth,k.height));const inner=keycapLoft(k.width-k.wall*2,k.depth-k.wall*2,k.topWidth-k.wall*2,k.topDepth-k.wall*2,k.height-k.topThickness+.5);inner.translate(0,0,-.4);solid=csg(solid,brush(inner),SUBTRACTION);const socketOuter=new THREE.CylinderGeometry(k.socketOuter/2,k.socketOuter/2,k.socketHeight,28);socketOuter.rotateX(Math.PI/2);socketOuter.translate(0,0,k.socketHeight/2+.2);let socket=brush(socketOuter);const total=k.crossTotal+k.stemTolerance*2,arm=k.crossArm+k.stemTolerance*2,g1=new THREE.BoxGeometry(total,arm,k.socketHeight+1),g2=new THREE.BoxGeometry(arm,total,k.socketHeight+1);g1.translate(0,0,k.socketHeight/2+.2);g2.translate(0,0,k.socketHeight/2+.2);socket=csg(socket,csg(brush(g1),brush(g2),ADDITION),SUBTRACTION);solid=csg(solid,socket,ADDITION);const g=solid.geometry.clone();g.rotateX(-Math.PI/2);g.rotateZ(THREE.MathUtils.degToRad(k.tilt));g.computeVertexNormals();return g}

function Controls({view,target=[0,2,0]}){const{camera,gl}=useThree(),ref=useRef();useEffect(()=>{const c=new ThreeOrbitControls(camera,gl.domElement);c.enableDamping=true;c.target.set(...target);ref.current=c;return()=>c.dispose()},[camera,gl]);useEffect(()=>{const map={Iso:[46,34,52],Top:[0,70,.01],Bottom:[0,-70,.01],Front:[0,10,70],Back:[0,10,-70],Left:[-70,10,0],Right:[70,10,0]},v=map[view]||map.Iso;camera.position.set(...v);camera.lookAt(...target);ref.current?.update()},[view,camera]);useFrame(()=>ref.current?.update());return null}
function Scene({geometry,view,color,wire,alpha,modelRef}){const mat=useMemo(()=>new THREE.MeshStandardMaterial({color,roughness:.38,metalness:.03,wireframe:wire,transparent:alpha,opacity:alpha?.56:1,side:THREE.DoubleSide}),[color,wire,alpha]);return<><ambientLight intensity={1.35}/><directionalLight position={[12,18,16]} intensity={2.2}/><mesh ref={modelRef} geometry={geometry} material={mat}/><gridHelper args={[220,220]}/><Controls view={view}/></>}
const Num=({label,value,onChange,step=.1,suffix='mm',min})=><label className="field"><span>{label}</span><div><input type="number" value={value} min={min} step={step} onChange={e=>onChange(Number(e.target.value))}/><b>{suffix}</b></div></label>;
const Sel=({label,value,onChange,children})=><label className="field"><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)}>{children}</select></label>;
function download(name,data,type){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([data],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),800)}

function App(){
 const modelRef=useRef(),[tool,setTool]=useState('Tray'),[view,setView]=useState('Iso'),[wire,setWire]=useState(false),[alpha,setAlpha]=useState(false),[color,setColor]=useState('#d7e2f2'),[selected,setSelected]=useState(0);
 const makeCells=(r,c)=>Array.from({length:r*c},()=>({enabled:true,unit:'1U',customW:19.4,customD:19.4,fitOffset:0}));
 const[tray,setTray]=useState({mode:'Pocket',rows:4,cols:6,pitchX:19.05,pitchY:19.05,edge:3.2,baseThickness:2.8,pocketDepth:7,topLip:1.6,taperDelta:1.0,globalClearance:0,outerRadius:3,fingerNotch:true,notchRadius:3.6,mountPlate:3,pegHeight:3.6,pegTotal:3.95,pegArm:1.05,supportRing:true,ringOuter:7,ringInner:5.4,ringHeight:1.2,cells:makeCells(4,6)});
 const[key,setKey]=useState({profile:'Cherry',width:18,depth:18,topWidth:13.2,topDepth:13.2,height:9.5,wall:1.2,topThickness:1.6,tilt:-6,socketOuter:5.5,socketHeight:4.2,crossTotal:4.1,crossArm:1.17,stemTolerance:.1});
 const patchTray=x=>setTray(v=>({...v,...x})),patchKey=x=>setKey(v=>({...v,...x}));
 const resizeGrid=(rows,cols)=>{const cells=Array.from({length:rows*cols},(_,i)=>tray.cells[i]||{enabled:true,unit:'1U',customW:19.4,customD:19.4,fitOffset:0});patchTray({rows,cols,cells});setSelected(0)};
 const setCell=(i,x)=>setTray(v=>({...v,cells:v.cells.map((c,idx)=>idx===i?{...c,...x}:c)}));
 const trayBuilt=useMemo(()=>{try{return buildTray(tray)}catch(e){console.error(e);return{geometry:new THREE.BoxGeometry(1,1,1),W:0,D:0,H:0}}},[tray]);
 const keyGeom=useMemo(()=>{try{return buildKeycap(key)}catch(e){console.error(e);return new THREE.BoxGeometry(1,1,1)}},[key]);
 const geometry=tool==='Tray'?trayBuilt.geometry:keyGeom;
 const exportStl=()=>{if(!modelRef.current)return;modelRef.current.updateMatrixWorld(true);const bin=new STLExporter().parse(modelRef.current,{binary:true});download(tool==='Tray'?'keycap_tray.stl':'keycap.stl',bin,'model/stl')};
 const exportJson=()=>download('keycap-studio.json',JSON.stringify({tool,tray,key},null,2),'application/json');
 const applyTrayPreset=(r,c)=>resizeGrid(r,c);
 const applyFit=name=>{const off=fitPreset[name];patchTray({cells:tray.cells.map(c=>({...c,fitOffset:off}))})};
 const testStrip=()=>{const cells=[-.15,0,.2].map((f)=>({enabled:true,unit:'1U',customW:19.4,customD:19.4,fitOffset:f}));patchTray({mode:'Pocket',rows:1,cols:3,pitchX:23,edge:4,cells});setSelected(1)};
 const cell=tray.cells[selected]||tray.cells[0];
 const warnings=[];if(tool==='Tray'&&tray.mode==='Pocket'&&tray.pocketDepth<5)warnings.push('Pocket depth dưới 5 mm có thể giữ keycap kém.');if(tool==='Tray'&&tray.mode==='Mount'&&tray.pegArm>1.2)warnings.push('Peg arm khá dày, nên in test trước khi cắm keycap.');if(tool==='Tray'&&trayBuilt.W>250)warnings.push('Khay rộng trên 250 mm, hãy kiểm tra kích thước bàn in.');if(tool==='Keycap'&&key.wall<.9)warnings.push('Wall keycap dưới 0.9 mm khá mỏng.');
 return <div className="app"><header><div className="brand"><div className="logo">K</div><div><h1>Keycap Studio</h1><p>Keycap + Tray Generator / STL thực</p></div></div><div className="modeSwitch"><button className={tool==='Keycap'?'active':''} onClick={()=>setTool('Keycap')}>Keycap</button><button className={tool==='Tray'?'active':''} onClick={()=>setTool('Tray')}>Tray Generator</button></div><div className="actions"><button onClick={exportJson}>JSON</button><button className="primary" onClick={exportStl}>Export STL</button></div></header>
 <main className="workspace"><aside className="left">
 {tool==='Tray'?<>
  <section><div className="sectionTitle"><h3>Tray type</h3><span>{tray.mode}</span></div><div className="seg"><button className={tray.mode==='Pocket'?'active':''} onClick={()=>patchTray({mode:'Pocket'})}>Pocket Tray</button><button className={tray.mode==='Mount'?'active':''} onClick={()=>patchTray({mode:'Mount'})}>MX Mount Tray</button></div><p className="desc">Pocket = nhét keycap vào ô. MX Mount = cắm keycap lên chốt chữ thập đực.</p></section>
  <section><h3>Layout</h3><div className="chips"><button onClick={()=>applyTrayPreset(3,5)}>3×5</button><button onClick={()=>applyTrayPreset(4,6)}>4×6</button><button onClick={()=>applyTrayPreset(5,7)}>5×7</button><button onClick={()=>applyTrayPreset(6,8)}>6×8</button></div><div className="two"><Num label="Rows" value={tray.rows} min={1} step={1} suffix="" onChange={v=>resizeGrid(Math.max(1,Math.min(10,v)),tray.cols)}/><Num label="Cols" value={tray.cols} min={1} step={1} suffix="" onChange={v=>resizeGrid(tray.rows,Math.max(1,Math.min(14,v)))}/></div><div className="cellGrid" style={{gridTemplateColumns:`repeat(${tray.cols},1fr)`}}>{tray.cells.map((c,i)=><button key={i} className={`${selected===i?'selected':''} ${!c.enabled?'disabled':''}`} onClick={()=>setSelected(i)}>{c.enabled?c.unit:'×'}</button>)}</div></section>
  <section><div className="sectionTitle"><h3>Selected cell #{selected+1}</h3><label className="miniToggle"><input type="checkbox" checked={cell.enabled} onChange={e=>setCell(selected,{enabled:e.target.checked})}/> enabled</label></div><Sel label="Unit" value={cell.unit} onChange={v=>setCell(selected,{unit:v})}>{[...Object.keys(units),'Custom'].map(u=><option key={u}>{u}</option>)}</Sel>{cell.unit==='Custom'&&<div className="two"><Num label="Custom width" value={cell.customW} onChange={v=>setCell(selected,{customW:v})}/><Num label="Custom depth" value={cell.customD} onChange={v=>setCell(selected,{customD:v})}/></div>}<Num label="Cell fit offset" value={cell.fitOffset} step={.05} onChange={v=>setCell(selected,{fitOffset:v})}/><div className="chips"><button onClick={()=>setCell(selected,{fitOffset:-.15})}>Tight</button><button onClick={()=>setCell(selected,{fitOffset:0})}>Normal</button><button onClick={()=>setCell(selected,{fitOffset:.2})}>Loose</button></div></section>
  {tray.mode==='Pocket'?<section><h3>Pocket geometry</h3><Num label="Pocket depth" value={tray.pocketDepth} onChange={v=>patchTray({pocketDepth:v})}/><Num label="Base thickness" value={tray.baseThickness} onChange={v=>patchTray({baseThickness:v})}/><Num label="Top lip" value={tray.topLip} onChange={v=>patchTray({topLip:v})}/><Num label="Taper delta" value={tray.taperDelta} onChange={v=>patchTray({taperDelta:v})}/><Num label="Global clearance" value={tray.globalClearance} step={.05} onChange={v=>patchTray({globalClearance:v})}/><label className="toggle"><input type="checkbox" checked={tray.fingerNotch} onChange={e=>patchTray({fingerNotch:e.target.checked})}/>Finger notch</label><button className="wide primary" onClick={testStrip}>Tạo test strip Tight / Normal / Loose</button></section>:<section><h3>MX male peg</h3><Num label="Peg total" value={tray.pegTotal} step={.05} onChange={v=>patchTray({pegTotal:v})}/><Num label="Peg arm" value={tray.pegArm} step={.05} onChange={v=>patchTray({pegArm:v})}/><Num label="Peg height" value={tray.pegHeight} onChange={v=>patchTray({pegHeight:v})}/><Num label="Plate thickness" value={tray.mountPlate} onChange={v=>patchTray({mountPlate:v})}/><label className="toggle"><input type="checkbox" checked={tray.supportRing} onChange={e=>patchTray({supportRing:e.target.checked})}/>Support ring</label></section>}
  <section><h3>Tray body</h3><Num label="Pitch X" value={tray.pitchX} onChange={v=>patchTray({pitchX:v})}/><Num label="Pitch Y" value={tray.pitchY} onChange={v=>patchTray({pitchY:v})}/><Num label="Edge margin" value={tray.edge} onChange={v=>patchTray({edge:v})}/><Num label="Outer radius" value={tray.outerRadius} onChange={v=>patchTray({outerRadius:v})}/></section>
 </>:<>
  <section><h3>Keycap profile</h3><div className="chips">{Object.keys(keyProfiles).map(n=><button key={n} className={key.profile===n?'active':''} onClick={()=>{const q=keyProfiles[n];patchKey({profile:n,height:q.height,topWidth:q.top,topDepth:q.top,tilt:q.tilt})}}>{n}</button>)}</div></section>
  <section><h3>Shell</h3><Num label="Bottom width" value={key.width} onChange={v=>patchKey({width:v})}/><Num label="Bottom depth" value={key.depth} onChange={v=>patchKey({depth:v})}/><Num label="Top width" value={key.topWidth} onChange={v=>patchKey({topWidth:v})}/><Num label="Top depth" value={key.topDepth} onChange={v=>patchKey({topDepth:v})}/><Num label="Height" value={key.height} onChange={v=>patchKey({height:v})}/><Num label="Wall" value={key.wall} onChange={v=>patchKey({wall:v})}/><Num label="Top thickness" value={key.topThickness} onChange={v=>patchKey({topThickness:v})}/><Num label="Tilt" value={key.tilt} suffix="°" onChange={v=>patchKey({tilt:v})}/></section>
  <section><h3>Cherry MX socket</h3><Num label="Cross total" value={key.crossTotal} step={.01} onChange={v=>patchKey({crossTotal:v})}/><Num label="Cross arm" value={key.crossArm} step={.01} onChange={v=>patchKey({crossArm:v})}/><Num label="FDM tolerance" value={key.stemTolerance} step={.05} onChange={v=>patchKey({stemTolerance:v})}/><Num label="Socket outer" value={key.socketOuter} onChange={v=>patchKey({socketOuter:v})}/><Num label="Socket height" value={key.socketHeight} onChange={v=>patchKey({socketHeight:v})}/></section>
 </>}
 </aside>
 <div className="viewer"><Canvas camera={{position:[46,34,52],fov:36}}><Scene geometry={geometry} view={view} color={color} wire={wire} alpha={alpha} modelRef={modelRef}/></Canvas><div className="viewerTop"><span className="statusDot"/>Live geometry</div><div className="hint">Drag xoay • Wheel zoom • Grid 1 mm</div></div>
 <aside className="inspector"><section><h3>View</h3><div className="viewgrid">{['Iso','Top','Bottom','Front','Back','Left','Right'].map(v=><button key={v} className={view===v?'active':''} onClick={()=>setView(v)}>{v}</button>)}</div><label className="toggle"><input type="checkbox" checked={wire} onChange={e=>setWire(e.target.checked)}/>Wireframe</label><label className="toggle"><input type="checkbox" checked={alpha} onChange={e=>setAlpha(e.target.checked)}/>Transparent</label><input className="color" type="color" value={color} onChange={e=>setColor(e.target.value)}/></section>
 <section><h3>Analysis</h3>{tool==='Tray'?<div className="stats"><span>Width <b>{trayBuilt.W.toFixed(1)} mm</b></span><span>Depth <b>{trayBuilt.D.toFixed(1)} mm</b></span><span>Height <b>{trayBuilt.H.toFixed(1)} mm</b></span><span>Cells <b>{tray.cells.filter(c=>c.enabled).length}</b></span></div>:<div className="stats"><span>Width <b>{key.width.toFixed(1)} mm</b></span><span>Depth <b>{key.depth.toFixed(1)} mm</b></span><span>Height <b>{key.height.toFixed(1)} mm</b></span></div>}{warnings.length?warnings.map((w,i)=><p className="warning" key={i}>{w}</p>):<p className="ok">Thông số hiện tại không có cảnh báo lớn.</p>}</section>
 {tool==='Tray'&&<section className="tip"><h3>Fit guidance</h3><p><b>Pocket Normal:</b> opening 1U mặc định 19.40 mm, có taper 1.0 mm xuống đáy để dễ nhét/rút.</p><p><b>MX Mount:</b> peg mặc định 3.95 × 1.05 mm. Nên test 3 peg trước khi in cả khay.</p><div className="chips"><button onClick={()=>applyFit('Tight')}>All Tight</button><button onClick={()=>applyFit('Normal')}>All Normal</button><button onClick={()=>applyFit('Loose')}>All Loose</button></div></section>}
 </aside></main></div>
}
createRoot(document.getElementById('root')).render(<App/>);
