import * as THREE from 'three';
import { RoundedBoxGeometry } from 'three/examples/jsm/geometries/RoundedBoxGeometry.js';
import { STLExporter } from 'three/examples/jsm/exporters/STLExporter.js';
import { Brush, Evaluator, ADDITION, SUBTRACTION } from 'three-bvh-csg';

export const config={maxDuration:60};
const ev=new Evaluator();ev.attributes=['position','normal'];
const U={'1U':{u:1,w:18,d:18},'1.25U':{u:1.25,w:22.75,d:18},'1.5U':{u:1.5,w:27.5,d:18},'1.75U':{u:1.75,w:32.25,d:18},'2U':{u:2,w:37,d:18},'2.25U':{u:2.25,w:41.75,d:18},'2.75U':{u:2.75,w:51.25,d:18},'6.25U':{u:6.25,w:117.5,d:18}};
function brush(g){const b=new Brush(g);b.updateMatrixWorld(true);return b}
function csg(a,b,op){a.updateMatrixWorld(true);b.updateMatrixWorld(true);const o=ev.evaluate(a,b,op);o.geometry.computeVertexNormals();return o}
function ring(w,d,r,z,seg=32){const rr=Math.max(.15,Math.min(r,w/2-.05,d/2-.05)),pc=Math.max(3,Math.floor(seg/4)),cs=[[w/2-rr,d/2-rr,0,Math.PI/2],[-w/2+rr,d/2-rr,Math.PI/2,Math.PI],[-w/2+rr,-d/2+rr,Math.PI,Math.PI*1.5],[w/2-rr,-d/2+rr,Math.PI*1.5,Math.PI*2]],pts=[];for(const[cx,cy,a0,a1]of cs)for(let i=0;i<pc;i++){const a=a0+(a1-a0)*i/pc;pts.push([cx+Math.cos(a)*rr,cy+Math.sin(a)*rr,z])}return pts}
function loft(bw,bd,tw,td,h,r=1.6,bottomZ=0){const levels=8,pos=[],idx=[],rs=[];for(let l=0;l<=levels;l++){const t=l/levels,pts=ring(THREE.MathUtils.lerp(bw,tw,t),THREE.MathUtils.lerp(bd,td,t),Math.min(r,bw*.2,bd*.2),bottomZ+t*h),start=pos.length/3;pts.forEach(p=>pos.push(...p));rs.push({start,count:pts.length})}const n=rs[0].count;for(let l=0;l<levels;l++)for(let i=0;i<n;i++){const a=rs[l].start+i,b=rs[l].start+(i+1)%n,c=rs[l+1].start+(i+1)%n,d=rs[l+1].start+i;idx.push(a,b,c,a,c,d)}const tc=pos.length/3;pos.push(0,0,bottomZ+h);for(let i=0;i<n;i++)idx.push(rs[levels].start+i,rs[levels].start+(i+1)%n,tc);const bc=pos.length/3;pos.push(0,0,bottomZ);for(let i=0;i<n;i++)idx.push(rs[0].start+(i+1)%n,rs[0].start+i,bc);const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));g.setIndex(idx);g.computeVertexNormals();return g}
function roundedBox(w,d,h,r=2){const rr=Math.max(.2,Math.min(r,w/2-.05,d/2-.05,h/2-.05)),g=new RoundedBoxGeometry(w,h,d,4,rr);g.rotateX(Math.PI/2);return g}
function cross(total,arm,h,x=0,y=0,z=0){const a=new THREE.BoxGeometry(total,arm,h),b=new THREE.BoxGeometry(arm,total,h);a.translate(x,y,z+h/2);b.translate(x,y,z+h/2);return csg(brush(a),brush(b),ADDITION)}
function socket(k,x=0,y=0){const og=new THREE.CylinderGeometry(k.socketOuter/2,k.socketOuter/2,k.socketHeight,32);og.rotateX(Math.PI/2);og.translate(x,y,k.socketHeight/2+.15);let s=brush(og);const total=k.crossTotal+k.tolerance*2,arm=k.crossArm+k.tolerance*2;s=csg(s,cross(total,arm,k.socketHeight+1,x,y,-.35),SUBTRACTION);return s}
function makeTray(t){const u=U[t.unit]||U['1U'],capW=Number(t.capW??u.w),capD=Number(t.capD??u.d),openW=capW+t.clearance*2+capW*t.shrink/100,openD=capD+t.clearance*2+capD*t.shrink/100,pitchX=Number(t.pitchX),pitchY=Number(t.pitchY),W=(t.cols-1)*pitchX+openW+t.edge*2,D=(t.rows-1)*pitchY+openD+t.edge*2;if(!(pitchX>0&&pitchY>0&&W>0&&D>0))throw new Error('Kích thước khay không hợp lệ');if(t.mode==='Hốc chứa'){const H=t.base+t.depth+t.lip,og=roundedBox(W,D,H,t.outerRadius);og.translate(0,0,H/2);let solid=brush(og);for(let r=0;r<t.rows;r++)for(let c=0;c<t.cols;c++){const x=(c-(t.cols-1)/2)*pitchX,y=((t.rows-1)/2-r)*pitchY,p=loft(Math.max(4,openW-t.taper),Math.max(4,openD-t.taper),openW,openD,t.depth+t.lip+.8,Math.min(1.2,t.slotRadius||1),0);p.translate(x,y,t.base-.2);solid=csg(solid,brush(p),SUBTRACTION);if(t.notch){const n=new THREE.CylinderGeometry(t.notchRadius,t.notchRadius,t.depth+2,28);n.rotateX(Math.PI/2);n.translate(x,y-openD/2+t.notchRadius*.35,t.base+t.depth*.55);solid=csg(solid,brush(n),SUBTRACTION)}}const g=solid.geometry.clone();g.rotateX(-Math.PI/2);g.computeVertexNormals();return g}const H=t.mountPlate+t.pegHeight,pg=roundedBox(W,D,t.mountPlate,t.outerRadius);pg.translate(0,0,t.mountPlate/2);let solid=brush(pg);for(let r=0;r<t.rows;r++)for(let c=0;c<t.cols;c++){const x=(c-(t.cols-1)/2)*pitchX,y=((t.rows-1)/2-r)*pitchY;solid=csg(solid,cross(t.pegTotal,t.pegArm,t.pegHeight,x,y,t.mountPlate-.05),ADDITION);if(t.ring){const ro=new THREE.CylinderGeometry(t.ringOuter/2,t.ringOuter/2,t.ringHeight,28),ri=new THREE.CylinderGeometry(t.ringInner/2,t.ringInner/2,t.ringHeight+1,28);ro.rotateX(Math.PI/2);ri.rotateX(Math.PI/2);ro.translate(x,y,t.mountPlate+t.ringHeight/2);ri.translate(x,y,t.mountPlate+t.ringHeight/2);solid=csg(solid,csg(brush(ro),brush(ri),SUBTRACTION),ADDITION)}}const g=solid.geometry.clone();g.rotateX(-Math.PI/2);g.computeVertexNormals();return g}
function makeKey(k){let solid=brush(loft(k.bottomW,k.bottomD,k.topW,k.topD,k.height,k.corner));const inner=loft(Math.max(2,k.bottomW-k.wall*2),Math.max(2,k.bottomD-k.wall*2),Math.max(2,k.topW-k.wall*2),Math.max(2,k.topD-k.wall*2),Math.max(.8,k.height-k.topThickness+.5),Math.max(.4,k.corner-k.wall*.45),-.45);solid=csg(solid,brush(inner),SUBTRACTION);if(k.dish>0){const radius=Math.max(18,Math.max(k.topW,k.topD)*2.6),sp=new THREE.SphereGeometry(radius,48,24);sp.translate(0,0,k.height+radius-k.dish);solid=csg(solid,brush(sp),SUBTRACTION)}solid=csg(solid,socket(k,0,0),ADDITION);if(k.stabilizers&&k.stabSpacing>0){const h=k.stabSpacing/2;solid=csg(solid,socket(k,-h,0),ADDITION);solid=csg(solid,socket(k,h,0),ADDITION)}const g=solid.geometry.clone();g.rotateX(-Math.PI/2);g.rotateZ(THREE.MathUtils.degToRad(k.tilt||0));g.computeVertexNormals();return g}
function toBuffer(v){if(v instanceof ArrayBuffer)return Buffer.from(v);if(ArrayBuffer.isView(v))return Buffer.from(v.buffer,v.byteOffset,v.byteLength);return Buffer.from(v)}
export default async function handler(req,res){if(req.method!=='POST')return res.status(405).json({error:'Chỉ hỗ trợ POST'});try{const{tool='Khay',tray,key}=req.body||{},geometry=tool==='Khay'?makeTray(tray):makeKey(key),mesh=new THREE.Mesh(geometry,new THREE.MeshBasicMaterial());mesh.updateMatrixWorld(true);const stl=new STLExporter().parse(mesh,{binary:true}),buf=toBuffer(stl);if(buf.length<84)throw new Error('STL rỗng');res.setHeader('Content-Type','model/stl');res.setHeader('Content-Disposition',`attachment; filename="${tool==='Khay'?'khay-keycap':'keycap'}.stl"`);res.setHeader('Content-Length',String(buf.length));res.status(200).send(buf)}catch(e){console.error(e);res.status(500).json({error:'Không thể tạo STL',detail:e?.message||String(e)})}}
