import { useMemo, useRef, useState } from "react";
import { AlertTriangle, Box, Download, RotateCcw, Save, Upload } from "lucide-react";
import { Viewer, type ViewOptions, type ViewName } from "./Viewer";
import { buildKeycap } from "./geometry";
import { DEFAULT_PARAMS, FDM_SAFE_04, PROFILES, SIZES, STAB_PRESETS, applyProfile, applySize, type KeycapParams, type ProfileId, type SizeId } from "./params";
import { download, exportJSON, exportOBJ, exportSTL, fileName } from "./export";

const NOZZLES=[.2,.4,.6]; const CLEARANCES=[0,.05,.1,.15,.2];
type RightTab="shape"|"stem"|"mfg"|"analysis";
function Btn({children,onClick,active=false,secondary=false,disabled=false,className=""}:{children:React.ReactNode;onClick?:()=>void;active?:boolean;secondary?:boolean;disabled?:boolean;className?:string}){return <button disabled={disabled} onClick={onClick} className={`${active?"bg-primary text-primary-foreground":"bg-background hover:bg-accent"} ${secondary?"bg-secondary":""} inline-flex items-center justify-center gap-1.5 rounded-md border border-border px-2.5 py-1.5 text-[11px] font-medium shadow-sm transition disabled:opacity-50 ${className}`}>{children}</button>}
function Panel({title,desc,children,right}:{title:string;desc?:string;children:React.ReactNode;right?:React.ReactNode}){return <section className="rounded-lg border border-border bg-card p-3.5"><header className="mb-3 flex items-start justify-between gap-2"><div><h3 className="text-[13px] font-semibold tracking-tight">{title}</h3>{desc&&<p className="mt-0.5 text-[11px] leading-snug text-muted-foreground">{desc}</p>}</div>{right}</header><div className="space-y-3">{children}</div></section>}
function NumberField({label,value,onChange,min,max,step=.1,unit="mm",hint,invalid=false}:{label:string;value:number;onChange:(v:number)=>void;min:number;max:number;step?:number;unit?:string;hint?:string;invalid?:boolean}){const clamp=(v:number)=>Math.min(max,Math.max(min,v));return <div className="space-y-1.5"><div className="flex items-center justify-between gap-2"><div><span className="text-xs font-medium">{label}</span>{hint&&<span title={hint} className="ml-1 cursor-help text-[10px] text-muted-foreground">ⓘ</span>}</div><div className="flex items-center gap-1"><input type="number" value={Number.isFinite(value)?value:0} step={step} min={min} max={max} onChange={e=>onChange(clamp(parseFloat(e.target.value)||0))} className={`h-7 w-20 rounded-md border bg-background px-2 text-right font-mono text-xs ${invalid?"border-destructive text-destructive":"border-input"}`}/><span className="w-6 text-[10px] text-muted-foreground">{unit}</span></div></div><input type="range" value={Math.min(max,Math.max(min,value))} min={min} max={max} step={step} onChange={e=>onChange(Number(e.target.value))} className="h-1.5 w-full cursor-pointer accent-blue-600"/></div>}
function Toggle({checked,onChange,label,disabled=false}:{checked:boolean;onChange:(v:boolean)=>void;label?:string;disabled?:boolean}){return <label className={`inline-flex items-center gap-2 text-[11px] ${disabled?"opacity-50":""}`}><input disabled={disabled} type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)} className="accent-blue-600"/>{label}</label>}
function Row({label,value}:{label:string;value:string}){return <div className="flex items-center justify-between gap-3 text-xs"><span className="text-muted-foreground">{label}</span><span className="text-right font-mono tabular-nums">{value}</span></div>}

export default function App(){
 const[p,setP]=useState<KeycapParams>(DEFAULT_PARAMS);const[opts,setOpts]=useState<ViewOptions>({view:"iso",ortho:false,wireframe:false,transparent:false,grid:true,axes:true,section:false,sectionAxis:"y"});const[tab,setTab]=useState<RightTab>("shape");const inputRef=useRef<HTMLInputElement>(null);const build=useMemo(()=>buildKeycap(p),[p]);const a=build.analysis;
 const set=<K extends keyof KeycapParams>(k:K,v:KeycapParams[K])=>setP(prev=>({...prev,[k]:v,sizeId:sizeAffecting(k)?"custom":prev.sizeId}));const setOpt=<K extends keyof ViewOptions>(k:K,v:ViewOptions[K])=>setOpts(o=>({...o,[k]:v}));
 const savePreset=()=>localStorage.setItem("keycap-preset",JSON.stringify(p));const loadPreset=()=>{const raw=localStorage.getItem("keycap-preset");if(raw)setP({...DEFAULT_PARAMS,...JSON.parse(raw)});};const onImport=(f:File)=>{const r=new FileReader();r.onload=()=>{try{const data=JSON.parse(String(r.result));setP({...DEFAULT_PARAMS,...(data.params??data)});}catch{alert("File JSON không hợp lệ")}};r.readAsText(f)};
 return <div className="flex h-screen flex-col bg-background text-foreground"><header className="flex shrink-0 items-center justify-between gap-4 border-b border-border bg-card px-5 py-2.5"><div className="flex items-center gap-2.5"><Box className="size-5 text-primary"/><div><h1 className="text-sm font-semibold tracking-tight">Keycap Generator</h1><p className="text-[11px] text-muted-foreground">Base gốc Lovable · keycap tham số hoá · Bambu Studio · mm</p></div></div><div className="flex items-center gap-2"><Btn onClick={()=>setP(DEFAULT_PARAMS)}><RotateCcw className="size-3.5"/>Reset</Btn><Btn onClick={savePreset}><Save className="size-3.5"/>Lưu preset</Btn><Btn onClick={()=>inputRef.current?.click()}><Upload className="size-3.5"/>Nhập JSON</Btn><input ref={inputRef} type="file" accept="application/json" className="hidden" onChange={e=>e.target.files?.[0]&&onImport(e.target.files[0])}/><div className="mx-1 h-6 w-px bg-border"/><Btn active onClick={()=>download(exportSTL(build.merged),fileName(p,"stl"))}><Download className="size-3.5"/>Export STL</Btn><Btn secondary onClick={()=>download(exportOBJ(build.merged),fileName(p,"obj"))}>OBJ</Btn><Btn secondary onClick={()=>download(exportJSON(p),fileName(p,"json"))}>JSON</Btn></div></header>
 <div className="grid min-h-0 flex-1 grid-cols-[260px_1fr_330px]"><aside className="min-h-0 space-y-3 overflow-y-auto border-r border-border p-3"><Panel title="Kích thước keycap" desc="Pitch chuẩn bàn phím là 19.05 mm mỗi 1U."><div className="grid grid-cols-2 gap-1.5">{(Object.keys(SIZES) as Exclude<SizeId,"custom">[]).map(id=><Btn key={id} active={p.sizeId===id} onClick={()=>setP(prev=>applySize(prev,id))}>{SIZES[id].label}</Btn>)}</div>{p.sizeId==="custom"&&<span className="inline-flex rounded-md border bg-secondary px-2 py-0.5 text-[10px]">Custom</span>}</Panel><Panel title="Profile" desc="Preset chỉ là điểm khởi đầu — mọi thông số vẫn sửa được."><div className="space-y-1.5">{(Object.keys(PROFILES) as ProfileId[]).map(id=><Btn key={id} active={p.profileId===id} className="w-full justify-between" onClick={()=>setP(prev=>applyProfile(prev,id))}><span>{PROFILES[id].label}</span><span className="font-mono text-[10px] opacity-70">{PROFILES[id].height} mm</span></Btn>)}</div></Panel><Panel title="Preset in ấn" desc="Ưu tiên dễ in hơn là quá mỏng."><Btn className="w-full" onClick={()=>setP(prev=>({...prev,...FDM_SAFE_04}))}>FDM safe – vòi 0.4 mm</Btn><Btn className="w-full" onClick={loadPreset}>Tải preset đã lưu</Btn></Panel><Panel title="Ghi chú" desc="Luôn in thử 1 phím trước khi in cả bộ."><p className="text-[11px] leading-relaxed text-muted-foreground">Kích thước stem và stabilizer nên đo lại trên phần cứng thực tế. Dung sai máy in khác nhau cần clearance khác nhau.</p></Panel></aside>
 <main className="relative min-h-0 bg-muted/40"><div className="absolute inset-x-0 top-0 z-10 flex flex-wrap items-center gap-1.5 border-b border-border bg-card/80 px-3 py-2 backdrop-blur">{([["iso","Iso"],["top","Trên"],["front","Trước"],["side","Cạnh"],["bottom","Đáy"]] as [ViewName,string][]).map(([v,l])=><Btn key={v} active={opts.view===v} onClick={()=>setOpt("view",v)}>{l}</Btn>)}<div className="mx-1 h-6 w-px bg-border"/>{([["ortho","Ortho"],["wireframe","Wireframe"],["transparent","Vỏ trong suốt"],["section","Cắt lát"],["grid","Lưới mm"],["axes","Trục XYZ"]] as [keyof ViewOptions,string][]).map(([k,l])=><Btn key={String(k)} secondary={Boolean(opts[k])} onClick={()=>setOpt(k,!opts[k] as never)}>{l}</Btn>)}{opts.section&&<Btn onClick={()=>setOpt("sectionAxis",opts.sectionAxis==="x"?"y":"x")}>Trục cắt: {opts.sectionAxis.toUpperCase()}</Btn>}</div><div className="absolute inset-0 pt-11"><Viewer build={build} opts={opts}/></div><div className="pointer-events-none absolute bottom-3 left-3 rounded-md border border-border bg-card/85 px-2.5 py-1.5 font-mono text-[10px] text-muted-foreground backdrop-blur">{a.bbox.x.toFixed(2)} × {a.bbox.y.toFixed(2)} × {a.bbox.z.toFixed(2)} mm · {a.triangles} tam giác</div></main>
 <aside className="min-h-0 overflow-y-auto border-l border-border p-3"><div className="grid grid-cols-4 rounded-lg bg-muted p-1">{([["shape","Thân"],["stem","Stem"],["mfg","In 3D"],["analysis","Phân tích"]] as [RightTab,string][]).map(([k,l])=><button key={k} onClick={()=>setTab(k)} className={`rounded-md px-2 py-1 text-[11px] font-medium ${tab===k?"bg-background shadow":"text-muted-foreground"}`}>{l}</button>)}</div>
 {tab==="shape"&&<div className="mt-3 space-y-3"><Panel title="Kích thước cơ bản"><NumberField label="Pitch" value={p.pitch} onChange={v=>set("pitch",v)} min={15} max={22} step={.05}/><NumberField label="Rộng đáy (X)" value={p.bottomWidth} onChange={v=>set("bottomWidth",v)} min={8} max={130}/><NumberField label="Sâu đáy (Y)" value={p.bottomDepth} onChange={v=>set("bottomDepth",v)} min={8} max={40}/><NumberField label="Rộng mặt trên" value={p.topWidth} onChange={v=>set("topWidth",v)} min={5} max={125} invalid={p.topWidth>p.bottomWidth}/><NumberField label="Sâu mặt trên" value={p.topDepth} onChange={v=>set("topDepth",v)} min={5} max={38} invalid={p.topDepth>p.bottomDepth}/><NumberField label="Chiều cao" value={p.height} onChange={v=>set("height",v)} min={4} max={20}/></Panel><Panel title="Hình dạng chi tiết"><NumberField label="Dày thành" value={p.wallThickness} onChange={v=>set("wallThickness",v)} min={.6} max={3} step={.05}/><NumberField label="Dày nóc" value={p.topThickness} onChange={v=>set("topThickness",v)} min={.6} max={4} step={.05}/><NumberField label="Độ cong sườn (taper)" value={p.sideDraft} onChange={v=>set("sideDraft",v)} min={0} max={12} step={.5} unit="°"/><NumberField label="Bo góc đáy" value={p.cornerRadius} onChange={v=>set("cornerRadius",v)} min={.2} max={5}/><NumberField label="Bo góc mặt trên" value={p.topCornerRadius} onChange={v=>set("topCornerRadius",v)} min={.2} max={6}/><NumberField label="Độ sâu dish" value={p.dishDepth} onChange={v=>set("dishDepth",v)} min={0} max={3} step={.05}/><NumberField label="Độ tù của dish" value={p.dishStrength} onChange={v=>set("dishStrength",v)} min={1} max={4} step={.1} unit=""/><NumberField label="Nghiêng mặt trên" value={p.topTilt} onChange={v=>set("topTilt",v)} min={-15} max={15} step={.5} unit="°"/><NumberField label="Bo mép vành trên" value={p.filletTop} onChange={v=>set("filletTop",v)} min={0} max={2} step={.05}/></Panel></div>}
 {tab==="stem"&&<div className="mt-3 space-y-3"><Panel title="Stem Cherry MX" desc="Chân chữ thập ở chính giữa keycap." right={<Toggle checked={p.stemEnabled} onChange={v=>set("stemEnabled",v)}/>}><NumberField label="Đường kính trụ stem" value={p.stemDiameter} onChange={v=>set("stemDiameter",v)} min={3} max={9}/><NumberField label="Chiều cao stem" value={p.stemHeight} onChange={v=>set("stemHeight",v)} min={1.5} max={9}/><NumberField label="Dài khe chữ thập" value={p.crossLength} onChange={v=>set("crossLength",v)} min={3} max={5.5} step={.05}/><NumberField label="Rộng khe chữ thập" value={p.crossWidth} onChange={v=>set("crossWidth",v)} min={.8} max={2.5} step={.05}/><div><span className="text-xs font-medium">Clearance cho FDM</span><div className="mt-1.5 flex gap-1.5">{CLEARANCES.map(c=><Btn key={c} active={p.stemClearance===c} className="flex-1 px-0 font-mono" onClick={()=>set("stemClearance",c)}>+{c.toFixed(2)}</Btn>)}</div></div><Btn className="w-full" onClick={()=>setP(prev=>({...prev,crossLength:4.1,crossWidth:1.35,stemDiameter:5.5}))}>Đặt lại “Cherry MX nominal”</Btn><Btn className="w-full" onClick={()=>{setOpt("view","bottom");setOpts(o=>({...o,transparent:true}))}}>Xem stem từ mặt dưới</Btn></Panel><Panel title="Stabilizer" desc={p.units>=2?"Chỉ khả dụng với keycap ≥ 2U. Hãy đo stabilizer thực tế trước khi in.":"Cần keycap ≥ 2U để bật stabilizer."} right={<Toggle disabled={p.units<2} checked={p.stabEnabled} onChange={v=>set("stabEnabled",v)}/>}><NumberField label="Khoảng cách tâm–tâm" value={p.stabSpacing} onChange={v=>set("stabSpacing",v)} min={10} max={140}/><div className="flex flex-wrap gap-1.5">{STAB_PRESETS.map(s=><Btn key={s.label} onClick={()=>set("stabSpacing",s.value)}>{s.label}</Btn>)}</div></Panel></div>}
 {tab==="mfg"&&<div className="mt-3 space-y-3"><Panel title="Vòi phun"><div className="flex gap-1.5">{NOZZLES.map(n=><Btn key={n} active={p.nozzle===n} className="flex-1 font-mono" onClick={()=>set("nozzle",n)}>{n.toFixed(1)} mm</Btn>)}</div></Panel><Panel title="Bù trừ kích thước"><NumberField label="Bù XY" value={p.xyCompensation} onChange={v=>set("xyCompensation",v)} min={-.5} max={.5} step={.01}/><NumberField label="Bù Z" value={p.zCompensation} onChange={v=>set("zCompensation",v)} min={-.5} max={.5} step={.01}/><NumberField label="Co ngót vật liệu" value={p.shrinkage} onChange={v=>set("shrinkage",v)} min={-2} max={2} step={.05} unit="%"/></Panel></div>}
 {tab==="analysis"&&<div className="mt-3 space-y-3"><Panel title="Kích thước bao (bounding box)"><dl className="grid grid-cols-3 gap-2 font-mono text-xs">{([["X",a.bbox.x],["Y",a.bbox.y],["Z",a.bbox.z]] as [string,number][]).map(([k,v])=><div key={k} className="rounded-md border bg-muted/50 p-2"><dt className="text-[10px] text-muted-foreground">{k}</dt><dd>{v.toFixed(2)} mm</dd></div>)}</dl></Panel><Panel title="Ước lượng vật liệu"><Row label="Thể tích đặc" value={`${(a.volume/1000).toFixed(3)} cm³`}/><Row label="Thành mỏng nhất" value={`${a.minWall.toFixed(2)} mm`}/><Row label="Số tam giác" value={String(a.triangles)}/><Row label="Trạng thái mesh" value={build.stems?"Vỏ kín + stem ghép chồng":"Vỏ kín, watertight"}/></Panel><Panel title="Cảnh báo">{a.warnings.length===0?<p className="text-[11px] text-muted-foreground">Không phát hiện vấn đề với thông số hiện tại.</p>:<ul className="space-y-2">{a.warnings.map(w=><li key={w} className="flex gap-2 rounded-md border border-destructive/30 bg-destructive/5 p-2 text-[11px]"><AlertTriangle className="mt-0.5 size-3.5 shrink-0 text-destructive"/>{w}</li>)}</ul>}</Panel></div>}
 </aside></div></div>
}
function sizeAffecting(k:keyof KeycapParams){return k==="bottomWidth"||k==="bottomDepth"||k==="topWidth"||k==="topDepth"||k==="pitch";}
