import * as THREE from "three";
import type { KeycapParams } from "./params";

function triangles(g:THREE.BufferGeometry){const pos=g.getAttribute("position").array as ArrayLike<number>;return{pos,count:pos.length/9};}
export function exportSTL(g:THREE.BufferGeometry):Blob{const{pos,count}=triangles(g),buffer=new ArrayBuffer(84+count*50),view=new DataView(buffer),header="Keycap Generator - binary STL - units: mm";for(let i=0;i<80;i++)view.setUint8(i,i<header.length?header.charCodeAt(i):32);view.setUint32(80,count,true);let o=84;const a=new THREE.Vector3(),b=new THREE.Vector3(),c=new THREE.Vector3(),n=new THREE.Vector3(),ab=new THREE.Vector3(),ac=new THREE.Vector3();for(let i=0;i<count;i++){const k=i*9;a.set(pos[k]!,pos[k+1]!,pos[k+2]!);b.set(pos[k+3]!,pos[k+4]!,pos[k+5]!);c.set(pos[k+6]!,pos[k+7]!,pos[k+8]!);ab.subVectors(b,a);ac.subVectors(c,a);n.crossVectors(ab,ac).normalize();view.setFloat32(o,n.x,true);view.setFloat32(o+4,n.y,true);view.setFloat32(o+8,n.z,true);for(let j=0;j<3;j++){const v=j===0?a:j===1?b:c;view.setFloat32(o+12+j*12,v.x,true);view.setFloat32(o+16+j*12,v.y,true);view.setFloat32(o+20+j*12,v.z,true);}view.setUint16(o+48,0,true);o+=50;}return new Blob([buffer],{type:"model/stl"});}
export function exportOBJ(g:THREE.BufferGeometry):Blob{const{pos,count}=triangles(g),lines:string[]=["# Keycap Generator OBJ (mm)","o keycap"];for(let i=0;i<count*9;i+=3)lines.push(`v ${pos[i]!.toFixed(4)} ${pos[i+1]!.toFixed(4)} ${pos[i+2]!.toFixed(4)}`);for(let i=0;i<count;i++)lines.push(`f ${i*3+1} ${i*3+2} ${i*3+3}`);return new Blob([lines.join("\n")],{type:"text/plain"});}
export function exportJSON(p:KeycapParams):Blob{return new Blob([JSON.stringify({app:"keycap-generator",version:1,params:p},null,2)],{type:"application/json"});}
export function fileName(p:KeycapParams,ext:string){const size=p.sizeId==="custom"?"custom":p.sizeId.toUpperCase(),f=(n:number)=>n.toFixed(1).replace(/\.0$/,"");return `keycap_${size}_${p.profileId}_${f(p.bottomWidth)}x${f(p.bottomDepth)}x${f(p.height)}.${ext}`;}
export function download(blob:Blob,name:string){const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
