import { Canvas } from "@react-three/fiber";
import { Grid, OrbitControls, PerspectiveCamera } from "@react-three/drei";
import * as THREE from "three";
import * as opentype from "opentype.js";
import { STLExporter } from "three/examples/jsm/exporters/STLExporter.js";
import { Copy, Download, Grid3X3, Plus, Trash2, Type } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { buildKeycap, mergeGeometries } from "./geometry";
import { DEFAULT_PARAMS, PROFILES, applyProfile, type KeycapParams, type ProfileId } from "./params";
import { ICONS, ICON_MAP } from "./iconLibraryV5";

type FontDef={id:string;name:string;url:string};
type Cap={id:string;text:string;color:string;textColor:string;fontId:string;fontSize:number;textDepth:number;iconId:string|null};
const FONTS:FontDef[]=[
 {id:"black",name:"Be Vietnam Pro Black",url:"https://raw.githubusercontent.com/google/fonts/main/ofl/bevietnampro/BeVietnamPro-Black.ttf"},
 {id:"extra",name:"Be Vietnam Pro ExtraBold",url:"https://raw.githubusercontent.com/google/fonts/main/ofl/bevietnampro/BeVietnamPro-ExtraBold.ttf"},
 {id:"bold",name:"Be Vietnam Pro Bold",url:"https://raw.githubusercontent.com/google/fonts/main/ofl/bevietnampro/BeVietnamPro-Bold.ttf"},
 {id:"medium",name:"Be Vietnam Pro Medium",url:"https://raw.githubusercontent.com/google/fonts/main/ofl/bevietnampro/BeVietnamPro-Medium.ttf"},
 {id:"regular",name:"Be Vietnam Pro Regular",url:"https://raw.githubusercontent.com/google/fonts/main/ofl/bevietnampro/BeVietnamPro-Regular.ttf"}
];
const FONT_MAP=Object.fromEntries(FONTS.map(f=>[f.id,f])) as Record<string,FontDef>;
const fontCache=new Map<string,opentype.Font>();
async function loadFont(id:string){if(fontCache.has(id))return fontCache.get(id)!;const d=FONT_MAP[id]||FONTS[0];const ab=await fetch(d.url).then(r=>{if(!r.ok)throw new Error(`Font ${r.status}`);return r.arrayBuffer()});const f=opentype.parse(ab);fontCache.set(id,f);return f}
function textGeo(font:opentype.Font,text:string,size:number,depth:number){const path=font.getPath(text,0,0,size);const sp=new THREE.ShapePath();for(const c of path.commands as any[]){if(c.type==='M')sp.moveTo(c.x,c.y);else if(c.type==='L')sp.lineTo(c.x,c.y);else if(c.type==='C')sp.bezierCurveTo(c.x1,c.y1,c.x2,c.y2,c.x,c.y);else if(c.type==='Q')sp.quadraticCurveTo(c.x1,c.y1,c.x,c.y);else if(c.type==='Z')sp.currentPath?.closePath()}const shapes=sp.toShapes(true);if(!shapes.length)return null;const g=new THREE.ExtrudeGeometry(shapes,{depth,bevelEnabled:true,bevelSize:.06,bevelThickness:.05,bevelSegments:2,curveSegments:10}).toNonIndexed();g.computeBoundingBox();const b=g.boundingBox!;g.translate(-(b.min.x+b.max.x)/2,-(b.min.y+b.max.y)/2,0);return g}
function pixelGeo(id:string,z:number){const icon=ICON_MAP[id];if(!icon)return null;const parts:THREE.BufferGeometry[]=[],px=.62,d=.5;for(let y=0;y<7;y++)for(let x=0;x<7;x++)if(icon.matrix[y][x]==='1'){const g=new THREE.BoxGeometry(px,px,d).toNonIndexed();g.translate((x-3)*px,(3-y)*px,z+d/2);parts.push(g)}return parts.length?mergeGeometries(parts):null}
function badgeGeo(z:number){const g=new THREE.BoxGeometry(6.5,6.2,.3).toNonIndexed();g.translate(0,0,z+.15);return g}
function saveSTL(items:{g:THREE.BufferGeometry;color:string}[]){const root=new THREE.Group();items.forEach(i=>root.add(new THREE.Mesh(i.g,new THREE.MeshBasicMaterial({color:i.color}))));root.updateMatrixWorld(true);const dv=new STLExporter().parse(root,{binary:true}) as DataView;const blob=new Blob([new Uint8Array(dv.buffer,dv.byteOffset,dv.byteLength)],{type:"model/stl"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="keycap-collection.stl";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function Scene({items}:{items:{g:THREE.BufferGeometry;color:string}[]}){return <Canvas shadows><color attach="background" args={["#f4f6f8"]}/><PerspectiveCamera makeDefault position={[38,-48,31]} fov={34} up={[0,0,1]}/><OrbitControls makeDefault target={[0,0,5]}/><ambientLight intensity={1.1}/><directionalLight position={[20,-30,45]} intensity={1.6}/>{items.map((x,i)=><mesh key={i} geometry={x.g}><meshStandardMaterial color={x.color} roughness={.4}/></mesh>)}<Grid args={[240,240]} rotation={[Math.PI/2,0,0]} cellSize={1} sectionSize={10} infiniteGrid fadeDistance={160}/></Canvas>}
const palette=["#f3c9cf","#f4e4a9","#cfeccf","#cddff1","#e1d0ec","#f3c9cf","#f4e4a9"];
const mk=(text:string,i:number):Cap=>({id:`cap-${Date.now()}-${i}-${Math.random()}`,text,color:palette[i%palette.length],textColor:"#55446f",fontId:"black",fontSize:5,textDepth:.55,iconId:null});

export default function KeycapAdvancedV5b(){
 const[p,setP]=useState<KeycapParams>({...DEFAULT_PARAMS,profileId:"xda",topWidth:14,topDepth:14,height:9,topTilt:0,sideDraft:3,dishDepth:0,stemHeight:4.7});
 const[caps,setCaps]=useState<Cap[]>(()=>[mk("A",0)]);const[selectedId,setSelectedId]=useState(caps[0].id);const[batch,setBatch]=useState("A");const[fonts,setFonts]=useState<Record<string,opentype.Font>>({});const[fontErr,setFontErr]=useState("");const selected=caps.find(c=>c.id===selectedId)||caps[0];
 useEffect(()=>{for(const id of Array.from(new Set(caps.map(c=>c.fontId))))if(!fonts[id])loadFont(id).then(f=>setFonts(s=>({...s,[id]:f}))).catch(e=>setFontErr(String(e)))},[caps]);
 const rebuild=()=>{const t=batch.trim().split(/\s+/u).filter(Boolean);const n=(t.length?t:["A"]).map((x,i)=>mk(x,i));setCaps(n);setSelectedId(n[0].id)};
 const patch=(x:Partial<Cap>)=>setCaps(cs=>cs.map(c=>c.id===selectedId?{...c,...x}:c));
 const add=()=>{const c=mk("KEY",caps.length);setCaps(cs=>[...cs,c]);setSelectedId(c.id);setBatch(b=>(b.trim()?b.trim()+" ":"")+"KEY")};
 const clone=()=>{if(!selected)return;const c={...selected,id:`clone-${Date.now()}`};setCaps(cs=>[...cs,c]);setSelectedId(c.id)};
 const del=()=>{if(caps.length<=1||!selected)return;const n=caps.filter(c=>c.id!==selected.id);setCaps(n);setSelectedId(n[0].id);setBatch(n.map(c=>c.text).join(" "))};
 const setField=(k:keyof KeycapParams,v:any)=>setP(x=>({...x,[k]:v}));
 const items=useMemo(()=>{const out:{g:THREE.BufferGeometry;color:string}[]=[];const base=buildKeycap(p),n=caps.length;caps.forEach((c,i)=>{const off=(i-(n-1)/2)*p.pitch;const body=base.shell.clone();body.translate(off,0,0);out.push({g:body,color:c.color});if(base.stems){const s=base.stems.clone();s.translate(off,0,0);out.push({g:s,color:"#d8dbe5"})}const f=fonts[c.fontId];if(f&&c.text){const g=textGeo(f,c.text,c.fontSize,c.textDepth);if(g){g.computeBoundingBox();const b=g.boundingBox!;const w=b.max.x-b.min.x,h=b.max.y-b.min.y,sc=Math.min(1,(p.topWidth-1.5)/Math.max(.1,w),(p.topDepth-1.5)/Math.max(.1,h));g.scale(sc,sc,1);g.translate(off,0,p.height+.08);out.push({g,color:c.textColor})}}if(c.iconId){const bg=badgeGeo(p.height+.05);bg.translate(off,0,0);out.push({g:bg,color:"#fffdf9"});const ig=pixelGeo(c.iconId,p.height+.38);if(ig){ig.translate(off,0,0);out.push({g:ig,color:ICON_MAP[c.iconId].color})}}});return out},[caps,p,fonts]);
 return <div className="grid h-full min-h-0 grid-cols-[310px_1fr_360px] bg-background">
  <aside className="space-y-3 overflow-y-auto border-r p-3"><section className="border bg-card p-3"><div className="flex items-center justify-between"><div><h2 className="text-sm font-semibold">KEYCAP COLLECTION V5</h2><p className="text-[9px] uppercase tracking-[.16em] text-muted-foreground">Multi-keycap thật · Vietnamese TTF</p></div><span className="border bg-muted px-2 py-1 font-mono text-[10px]">{caps.length} keycap</span></div></section><section className="space-y-2 border bg-card p-3"><h3 className="text-[10px] font-semibold uppercase">Tạo nhanh nhiều keycap</h3><p className="text-[9px] text-muted-foreground">Khoảng trắng hoặc xuống dòng = thêm 1 keycap.</p><textarea value={batch} onChange={e=>setBatch(e.target.value)} rows={4} placeholder={'A B C D E\nViết ệ Đ ư ơ'} className="w-full border bg-background p-2 font-mono text-xs"/><button onClick={rebuild} className="h-9 w-full bg-primary text-[10px] font-medium text-primary-foreground">Tạo / cập nhật dãy keycap</button><div className="flex flex-wrap gap-1">{caps.map((c,i)=><button key={c.id} onClick={()=>setSelectedId(c.id)} className={`border px-2 py-1 text-[9px] ${selectedId===c.id?"border-primary bg-primary/5":""}`}>{i+1}. {c.text}</button>)}</div><div className="grid grid-cols-3 gap-1"><button onClick={add} className="flex h-8 items-center justify-center gap-1 border text-[9px]"><Plus className="size-3"/>Thêm</button><button onClick={clone} className="flex h-8 items-center justify-center gap-1 border text-[9px]"><Copy className="size-3"/>Clone</button><button onClick={del} className="flex h-8 items-center justify-center gap-1 border text-[9px] text-red-600"><Trash2 className="size-3"/>Xóa</button></div></section><section className="space-y-2 border bg-card p-3"><h3 className="text-[10px] font-semibold uppercase">Thông số chung</h3><div className="grid grid-cols-5 gap-1">{(Object.keys(PROFILES) as ProfileId[]).map(id=><button key={id} onClick={()=>setP(x=>({...applyProfile(x,id),dishDepth:x.dishDepth,stemHeight:4.7}))} className={`border px-1 py-1 text-[9px] ${p.profileId===id?"bg-primary text-primary-foreground":""}`}>{PROFILES[id].label}</button>)}</div>{[["Dish depth","dishDepth",.05],["Stem height","stemHeight",.05],["Pitch","pitch",.05]].map(([l,k,st])=><label key={String(k)} className="grid grid-cols-[1fr_90px] items-center text-[10px]">{l}<input type="number" value={Number(p[k as keyof KeycapParams])} step={Number(st)} onChange={e=>setField(k as keyof KeycapParams,Number(e.target.value))} className="h-8 border bg-background px-2 text-right"/></label>)}</section></aside>
  <main className="min-h-0"><Scene items={items}/></main>
  <aside className="space-y-3 overflow-y-auto border-l p-3">{selected&&<><section className="space-y-2 border bg-card p-3"><div className="flex items-center gap-2"><Type className="size-4"/><h3 className="text-[10px] font-semibold uppercase">Keycap {caps.findIndex(c=>c.id===selected.id)+1}</h3></div><label className="text-[9px]">Text<input value={selected.text} onChange={e=>patch({text:e.target.value})} className="mt-1 h-9 w-full border bg-background px-2 text-sm"/></label><p className="text-[9px] text-emerald-700">Tiếng Việt thật: Viết, ệ, Đ, ă, â, ê, ô, ơ, ư...</p><label className="text-[9px]">Font<select value={selected.fontId} onChange={e=>patch({fontId:e.target.value})} className="mt-1 h-9 w-full border bg-background px-2">{FONTS.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><div className="grid grid-cols-2 gap-2"><label className="text-[9px]">Cỡ chữ<input type="number" value={selected.fontSize} step=.1 onChange={e=>patch({fontSize:Number(e.target.value)})} className="mt-1 h-8 w-full border bg-background px-2"/></label><label className="text-[9px]">Độ nổi<input type="number" value={selected.textDepth} step=.05 onChange={e=>patch({textDepth:Number(e.target.value)})} className="mt-1 h-8 w-full border bg-background px-2"/></label></div><div className="grid grid-cols-2 gap-2"><label className="text-[9px]">Màu keycap<input type="color" value={selected.color} onChange={e=>patch({color:e.target.value})} className="mt-1 h-8 w-full border"/></label><label className="text-[9px]">Màu chữ<input type="color" value={selected.textColor} onChange={e=>patch({textColor:e.target.value})} className="mt-1 h-8 w-full border"/></label></div>{fontErr&&<p className="text-[9px] text-red-600">{fontErr}</p>}</section><section className="border bg-card p-3"><div className="mb-2 flex items-center gap-2"><Grid3X3 className="size-4"/><h3 className="text-[10px] font-semibold uppercase">Icon Library · 28</h3></div><div className="grid grid-cols-7 gap-1">{ICONS.map(ic=><button key={ic.id} title={ic.name} onClick={()=>patch({iconId:selected.iconId===ic.id?null:ic.id})} className={`aspect-square border p-1 ${selected.iconId===ic.id?"border-primary bg-primary/10":"bg-[#fbfaf7]"}`}><div className="grid h-full grid-cols-7 grid-rows-7">{ic.matrix.flatMap((r,y)=>Array.from(r).map((v,x)=><span key={`${x}-${y}`} style={{background:v==='1'?ic.color:'transparent'}}/>))}</div></button>)}</div><button onClick={()=>patch({iconId:null})} className="mt-2 h-8 w-full border text-[9px]">Bỏ icon</button></section></>}<section className="sticky bottom-0 border bg-card p-3"><button onClick={()=>saveSTL(items)} className="flex h-10 w-full items-center justify-center gap-2 bg-primary text-[10px] font-medium text-primary-foreground"><Download className="size-4"/>Export {caps.length} keycap STL</button></section></aside>
 </div>
}
