import { Canvas } from "@react-three/fiber";
import { Grid, OrbitControls, PerspectiveCamera, TransformControls } from "@react-three/drei";
import * as THREE from "three";
import { STLExporter } from "three/examples/jsm/exporters/STLExporter.js";
import { FontLoader, type Font } from "three/examples/jsm/loaders/FontLoader.js";
import { TextGeometry } from "three/examples/jsm/geometries/TextGeometry.js";
import { useEffect, useMemo, useRef, useState } from "react";
import { Copy, Download, Eye, EyeOff, Lock, Plus, RotateCcw, Search, Trash2, Unlock, WandSparkles } from "lucide-react";
import { buildKeycap, mergeGeometries } from "./geometry";
import { DEFAULT_PARAMS, PROFILES, SIZES, applyProfile, applySize, type KeycapParams, type ProfileId, type SizeId } from "./params";

type Vec3=[number,number,number];
type Mode="translate"|"rotate"|"scale";
type Align="left"|"center"|"right";
type VAlign="top"|"middle"|"bottom";
type Placement="tl"|"tc"|"tr"|"ml"|"mc"|"mr"|"bl"|"bc"|"br";
type FitMode="none"|"width"|"box";
type ExportMode="combined"|"body"|"stem"|"legends";
type FontCategory="all"|"serif"|"sans"|"display"|"mono";
type ObjState={visible:boolean;locked:boolean;color:string;position:Vec3;rotation:Vec3;scale:Vec3};
type FontDef={id:string;name:string;category:Exclude<FontCategory,"all">;url:string;preview:string;fdm:boolean};
type LegendCfg={id:string;text:string;fontId:string;size:number;depth:number;letterSpacing:number;lineHeight:number;align:Align;vAlign:VAlign;bevel:boolean;bevelSize:number;bevelThickness:number;zLift:number;placement:Placement;fit:FitMode};

const FONT_BASE="https://threejs.org/examples/fonts/";
const FONTS:FontDef[]=[
 {id:"gentilis-bold",name:"Gentilis Bold",category:"serif",url:FONT_BASE+"gentilis_bold.typeface.json",preview:"Georgia,serif",fdm:true},
 {id:"gentilis",name:"Gentilis",category:"serif",url:FONT_BASE+"gentilis_regular.typeface.json",preview:"Georgia,serif",fdm:true},
 {id:"optimer-bold",name:"Optimer Bold",category:"display",url:FONT_BASE+"optimer_bold.typeface.json",preview:"Trebuchet MS,sans-serif",fdm:true},
 {id:"optimer",name:"Optimer",category:"display",url:FONT_BASE+"optimer_regular.typeface.json",preview:"Trebuchet MS,sans-serif",fdm:true},
 {id:"helvetiker-bold",name:"Helvetiker Bold",category:"sans",url:FONT_BASE+"helvetiker_bold.typeface.json",preview:"Arial Black,Arial,sans-serif",fdm:true},
 {id:"helvetiker",name:"Helvetiker",category:"sans",url:FONT_BASE+"helvetiker_regular.typeface.json",preview:"Arial,sans-serif",fdm:true},
 {id:"droid-serif-bold",name:"Droid Serif Bold",category:"serif",url:FONT_BASE+"droid/droid_serif_bold.typeface.json",preview:"Georgia,serif",fdm:true},
 {id:"droid-serif",name:"Droid Serif",category:"serif",url:FONT_BASE+"droid/droid_serif_regular.typeface.json",preview:"Georgia,serif",fdm:true},
 {id:"droid-sans-bold",name:"Droid Sans Bold",category:"sans",url:FONT_BASE+"droid/droid_sans_bold.typeface.json",preview:"Arial,sans-serif",fdm:true},
 {id:"droid-sans",name:"Droid Sans",category:"sans",url:FONT_BASE+"droid/droid_sans_regular.typeface.json",preview:"Arial,sans-serif",fdm:true},
 {id:"droid-mono",name:"Droid Sans Mono",category:"mono",url:FONT_BASE+"droid/droid_sans_mono_regular.typeface.json",preview:"Courier New,monospace",fdm:true},
];
const FONT_MAP=Object.fromEntries(FONTS.map(f=>[f.id,f])) as Record<string,FontDef>;
const fontCache=new Map<string,Font>();
async function loadFont(id:string){if(fontCache.has(id))return fontCache.get(id)!;const def=FONT_MAP[id]||FONTS[0];const json=await fetch(def.url).then(r=>{if(!r.ok)throw new Error(String(r.status));return r.json()});const font=new FontLoader().parse(json);fontCache.set(id,font);return font;}

const FIXED_LABEL:Record<string,string>={body:"Body / vỏ keycap",stem:"Stem giữa",stabL:"Stabilizer trái",stabR:"Stabilizer phải"};
const FIXED_STATE:Record<string,ObjState>={
 body:{visible:true,locked:false,color:"#f3c9cf",position:[0,0,0],rotation:[0,0,0],scale:[1,1,1]},
 stem:{visible:true,locked:false,color:"#d8dbe5",position:[0,0,0],rotation:[0,0,0],scale:[1,1,1]},
 stabL:{visible:true,locked:false,color:"#d8dbe5",position:[0,0,0],rotation:[0,0,0],scale:[1,1,1]},
 stabR:{visible:true,locked:false,color:"#d8dbe5",position:[0,0,0],rotation:[0,0,0],scale:[1,1,1]},
};
const legendState=():ObjState=>({visible:true,locked:false,color:"#55446f",position:[0,0,0],rotation:[0,0,0],scale:[1,1,1]});
const newLegend=(id="legend-1"):LegendCfg=>({id,text:"A",fontId:"gentilis-bold",size:4.4,depth:.55,letterSpacing:0,lineHeight:1.12,align:"center",vAlign:"middle",bevel:true,bevelSize:.06,bevelThickness:.05,zLift:.1,placement:"mc",fit:"box"});
const cloneFixed=()=>structuredClone(FIXED_STATE) as Record<string,ObjState>;
const labelOf=(id:string,legends:LegendCfg[])=>FIXED_LABEL[id]??`Legend · ${legends.find(x=>x.id===id)?.text || id.replace("legend-","")}`;

function sliceGeo(g:THREE.BufferGeometry,start:number,count:number){const a=g.getAttribute("position").array as Float32Array,out=new Float32Array(a.slice(start*3,(start+count)*3)),x=new THREE.BufferGeometry();x.setAttribute("position",new THREE.BufferAttribute(out,3));x.computeVertexNormals();return x;}
function splitStems(p:KeycapParams,g:THREE.BufferGeometry|null){if(!g||!p.stemEnabled)return{} as Record<string,THREE.BufferGeometry>;const n=p.stabEnabled&&p.units>=2?3:1,total=g.getAttribute("position").count,each=Math.floor(total/n),r:Record<string,THREE.BufferGeometry>={stem:sliceGeo(g,0,each)};if(n===3){r.stabR=sliceGeo(g,each,each);r.stabL=sliceGeo(g,each*2,total-each*2)}return r;}
function charGeometry(font:Font,ch:string,cfg:LegendCfg){if(ch===" ")return null;const g=new TextGeometry(ch,{font,size:cfg.size,depth:cfg.depth,curveSegments:12,bevelEnabled:cfg.bevel,bevelSize:cfg.bevel?cfg.bevelSize:0,bevelThickness:cfg.bevel?cfg.bevelThickness:0,bevelSegments:2});g.computeBoundingBox();return g.toNonIndexed();}
function makeTextLine(font:Font,text:string,cfg:LegendCfg){const pieces:THREE.BufferGeometry[]=[];let cursor=0;for(const ch of Array.from(text||" ")){const g=charGeometry(font,ch,cfg);if(!g){cursor+=cfg.size*.36+cfg.letterSpacing;continue}g.computeBoundingBox();const b=g.boundingBox!;const w=Math.max(.01,b.max.x-b.min.x);g.translate(cursor-b.min.x,0,0);pieces.push(g);cursor+=w+cfg.letterSpacing;}if(!pieces.length)return null;const merged=mergeGeometries(pieces);merged.computeBoundingBox();const b=merged.boundingBox!;const dx=cfg.align==="left"?-b.min.x:cfg.align==="right"?-b.max.x:-(b.min.x+b.max.x)/2;merged.translate(dx,0,0);return merged;}
function makeLegend(font:Font|null,cfg:LegendCfg,p:KeycapParams){if(!font||!cfg.text.trim())return null;const lines=cfg.text.split("\n").slice(0,4),parts:THREE.BufferGeometry[]=[];const lineStep=cfg.size*cfg.lineHeight;for(let i=0;i<lines.length;i++){const line=makeTextLine(font,lines[i],cfg);if(!line)continue;line.translate(0,-i*lineStep,0);parts.push(line);}if(!parts.length)return null;const g=mergeGeometries(parts);g.computeBoundingBox();let b=g.boundingBox!;let dy=cfg.vAlign==="top"?-b.max.y:cfg.vAlign==="bottom"?-b.min.y:-(b.min.y+b.max.y)/2;g.translate(0,dy,0);g.computeBoundingBox();b=g.boundingBox!;const width=Math.max(.01,b.max.x-b.min.x),height=Math.max(.01,b.max.y-b.min.y);const safeW=Math.max(1,p.topWidth-2),safeH=Math.max(1,p.topDepth-2);let scale=1;if(cfg.fit==="width")scale=Math.min(1,safeW/width);if(cfg.fit==="box")scale=Math.min(1,safeW/width,safeH/height);if(scale<1)g.scale(scale,scale,1);g.translate(0,0,Math.max(0,p.height-p.dishDepth)+cfg.zLift);g.computeVertexNormals();return g;}
function placementXY(place:Placement,p:KeycapParams):[number,number]{const x=p.topWidth*.28,y=p.topDepth*.28;const map:Record<Placement,[number,number]>={tl:[-x,y],tc:[0,y],tr:[x,y],ml:[-x,0],mc:[0,0],mr:[x,0],bl:[-x,-y],bc:[0,-y],br:[x,-y]};return map[place];}
function applyState(g:THREE.BufferGeometry,s:ObjState){const c=g.clone(),m=new THREE.Matrix4(),q=new THREE.Quaternion().setFromEuler(new THREE.Euler(...s.rotation.map(THREE.MathUtils.degToRad) as Vec3));m.compose(new THREE.Vector3(...s.position),q,new THREE.Vector3(...s.scale));c.applyMatrix4(m);return c;}
function saveSTL(name:string,entries:[THREE.BufferGeometry,ObjState][]) {const root=new THREE.Group();for(const [g,s] of entries){if(!s.visible)continue;root.add(new THREE.Mesh(applyState(g,s),new THREE.MeshBasicMaterial()))}root.updateMatrixWorld(true);const v=new STLExporter().parse(root,{binary:true}) as DataView,blob=new Blob([new Uint8Array(v.buffer,v.byteOffset,v.byteLength)],{type:"model/stl"}),u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function exportByMode(mode:ExportMode,objects:Record<string,THREE.BufferGeometry>,state:Record<string,ObjState>){let ids=Object.keys(objects);if(mode==="body")ids=ids.filter(x=>x==="body");if(mode==="stem")ids=ids.filter(x=>x==="stem"||x.startsWith("stab"));if(mode==="legends")ids=ids.filter(x=>x.startsWith("legend-"));const entries=ids.filter(id=>state[id]?.visible).map(id=>[objects[id],state[id]] as [THREE.BufferGeometry,ObjState]);if(entries.length)saveSTL(`keycap-${mode}.stl`,entries);}

function N({l,v,set,step=.1,min,max}:{l:string;v:number;set:(n:number)=>void;step?:number;min?:number;max?:number}){return <label className="grid grid-cols-[1fr_86px] items-center gap-2 text-[11px]"><span>{l}</span><input className="h-8 border bg-background px-2 text-right font-mono" type="number" value={v} step={step} min={min} max={max} onChange={e=>set(Number(e.target.value))}/></label>}
function V({title,v,set}:{title:string;v:Vec3;set:(v:Vec3)=>void}){return <div className="border p-2"><div className="mb-2 text-[10px] font-semibold uppercase tracking-wide">{title}</div><div className="grid grid-cols-3 gap-1">{[0,1,2].map(i=><label key={i} className="text-[9px] text-muted-foreground">{"XYZ"[i]}<input className="mt-1 h-7 w-full border bg-background px-1 text-right font-mono text-[10px]" type="number" value={Number(v[i].toFixed(3))} step={title==="Scale"?.05:.1} onChange={e=>{const a=[...v] as Vec3;a[i]=Number(e.target.value);set(a)}}/></label>)}</div></div>}
function ObjMesh({g,s,selected,mode,onSelect,onPatch}:{g:THREE.BufferGeometry;s:ObjState;selected:boolean;mode:Mode;onSelect:()=>void;onPatch:(x:Partial<ObjState>)=>void}){const ref=useRef<THREE.Mesh>(null);const mesh=<mesh ref={ref} geometry={g} position={s.position} rotation={s.rotation.map(THREE.MathUtils.degToRad) as Vec3} scale={s.scale} onClick={e=>{e.stopPropagation();onSelect()}}><meshStandardMaterial color={selected?"#f59e0b":s.color} roughness={.38}/></mesh>;if(!selected||s.locked)return mesh;return <TransformControls mode={mode} space="world" onMouseUp={()=>{const m=ref.current;if(!m)return;onPatch({position:m.position.toArray() as Vec3,rotation:[THREE.MathUtils.radToDeg(m.rotation.x),THREE.MathUtils.radToDeg(m.rotation.y),THREE.MathUtils.radToDeg(m.rotation.z)],scale:m.scale.toArray() as Vec3})}}>{mesh}</TransformControls>}
function SafeArea({p}:{p:KeycapParams}){const w=Math.max(1,p.topWidth-2),h=Math.max(1,p.topDepth-2),pts=[new THREE.Vector3(-w/2,-h/2,p.height+.08),new THREE.Vector3(w/2,-h/2,p.height+.08),new THREE.Vector3(w/2,h/2,p.height+.08),new THREE.Vector3(-w/2,h/2,p.height+.08),new THREE.Vector3(-w/2,-h/2,p.height+.08)],g=new THREE.BufferGeometry().setFromPoints(pts);return <line geometry={g}><lineBasicMaterial color="#7c3aed" transparent opacity={.35}/></line>}
function Scene({objects,state,selected,setSelected,mode,patch,p}:{objects:Record<string,THREE.BufferGeometry>;state:Record<string,ObjState>;selected:string;setSelected:(x:string)=>void;mode:Mode;patch:(id:string,x:Partial<ObjState>)=>void;p:KeycapParams}){return <Canvas shadows><color attach="background" args={["#f4f6f8"]}/><PerspectiveCamera makeDefault position={[28,-34,26]} fov={36} up={[0,0,1]}/><OrbitControls makeDefault target={[0,0,5]}/><ambientLight intensity={1}/><directionalLight position={[25,-30,40]} intensity={1.65}/>{Object.keys(objects).map(id=>{const g=objects[id],s=state[id];return g&&s?.visible?<ObjMesh key={id} g={g} s={s} selected={selected===id} mode={mode} onSelect={()=>setSelected(id)} onPatch={x=>patch(id,x)}/>:null})}<SafeArea p={p}/><Grid args={[200,200]} rotation={[Math.PI/2,0,0]} cellSize={1} sectionSize={10} infiniteGrid fadeDistance={120}/><axesHelper args={[15]}/></Canvas>}

export default function KeycapAdvancedV4(){
 const[p,setP]=useState<KeycapParams>({...DEFAULT_PARAMS,dishDepth:0});
 const[fonts,setFonts]=useState<Record<string,Font>>({});
 const[fontError,setFontError]=useState("");
 const[legends,setLegends]=useState<LegendCfg[]>([newLegend()]);
 const[state,setState]=useState<Record<string,ObjState>>(()=>({...cloneFixed(),"legend-1":legendState()}));
 const[selected,setSelected]=useState<string>("legend-1");
 const[mode,setMode]=useState<Mode>("translate");
 const[fontQuery,setFontQuery]=useState("");
 const[fontCat,setFontCat]=useState<FontCategory>("all");
 const[exportMode,setExportMode]=useState<ExportMode>("combined");
 const build=useMemo(()=>buildKeycap(p),[p]);
 const stemParts=useMemo(()=>splitStems(p,build.stems),[p,build.stems]);
 const activeLegend=legends.find(l=>l.id===selected)||legends[0];
 useEffect(()=>{const ids=Array.from(new Set(legends.map(l=>l.fontId)));for(const id of ids)if(!fonts[id])loadFont(id).then(font=>setFonts(x=>({...x,[id]:font}))).catch(()=>setFontError(`Không tải được font ${FONT_MAP[id]?.name||id}`));},[legends]);
 const legendGeos=useMemo(()=>{const out:Record<string,THREE.BufferGeometry>={};for(const l of legends){const g=makeLegend(fonts[l.fontId]||null,l,p);if(!g)continue;const [x,y]=placementXY(l.placement,p);g.translate(x,y,0);out[l.id]=g;}return out},[fonts,legends,p]);
 const objects=useMemo(()=>({body:build.shell,...stemParts,...legendGeos}) as Record<string,THREE.BufferGeometry>,[build.shell,stemParts,legendGeos]);
 const patch=(id:string,x:Partial<ObjState>)=>setState(s=>({...s,[id]:{...(s[id]||legendState()),...x}}));
 const set=<K extends keyof KeycapParams>(k:K,v:KeycapParams[K])=>setP(x=>({...x,[k]:v}));
 const updateLegend=(id:string,x:Partial<LegendCfg>)=>setLegends(ls=>ls.map(l=>l.id===id?{...l,...x}:l));
 const addLegend=()=>{if(legends.length>=8)return;const id=`legend-${Date.now()}`;setLegends(ls=>[...ls,newLegend(id)]);setState(s=>({...s,[id]:legendState()}));setSelected(id)};
 const duplicateLegend=(id:string)=>{if(legends.length>=8)return;const src=legends.find(l=>l.id===id);if(!src)return;const nid=`legend-${Date.now()}`;setLegends(ls=>[...ls,{...src,id:nid}]);setState(s=>({...s,[nid]:structuredClone(s[id]||legendState())}));setSelected(nid)};
 const removeLegend=(id:string)=>{if(legends.length<=1)return;setLegends(ls=>ls.filter(l=>l.id!==id));setState(s=>{const n={...s};delete n[id];return n});setSelected("body")};
 const ids=Object.keys(objects).filter(id=>objects[id]);
 const resetObject=(id:string)=>patch(id,structuredClone(FIXED_STATE[id]||legendState()));
 const applyPlacement=(id:string,place:Placement)=>{updateLegend(id,{placement:place});patch(id,{position:[0,0,state[id]?.position?.[2]||0]})};
 const filteredFonts=FONTS.filter(f=>(fontCat==="all"||f.category===fontCat)&&(`${f.name} ${f.category}`.toLowerCase().includes(fontQuery.toLowerCase())));
 const pastelPreset=()=>{setP(x=>({...x,dishDepth:0}));setLegends(ls=>ls.map((l,i)=>i?l:{...l,fontId:"gentilis-bold",size:4.4,depth:.55,bevel:true,bevelSize:.06,bevelThickness:.05,fit:"box"}));patch(legends[0].id,{color:"#55446f",scale:[1,1,1]});patch("body",{color:"#f3c9cf"});};
 return <div className="grid h-full min-h-0 grid-cols-[300px_1fr_360px] bg-background">
  <aside className="space-y-3 overflow-y-auto border-r p-3 pt-3">
   <section className="border bg-card p-3"><div className="flex items-center justify-between"><div><h2 className="text-sm font-semibold">KEYCAP</h2><p className="text-[9px] uppercase tracking-[.18em] text-muted-foreground">Shape · stem · print</p></div><button onClick={pastelPreset} className="flex h-8 items-center gap-1 border px-2 text-[10px]"><WandSparkles className="size-3"/>Pastel Clicker</button></div></section>
   <section className="border bg-card p-3"><h3 className="mb-2 text-[10px] font-semibold uppercase tracking-wide">Size / Profile</h3><div className="grid grid-cols-4 gap-1">{(Object.keys(SIZES) as Exclude<SizeId,"custom">[]).map(id=><button key={id} onClick={()=>setP(x=>applySize(x,id))} className={`border px-1 py-1 text-[9px] ${p.sizeId===id?"bg-primary text-primary-foreground":""}`}>{SIZES[id].label}</button>)}</div><div className="mt-2 grid grid-cols-5 gap-1">{(Object.keys(PROFILES) as ProfileId[]).map(id=><button key={id} onClick={()=>setP(x=>({...applyProfile(x,id),dishDepth:x.dishDepth}))} className={`border px-1 py-1 text-[9px] ${p.profileId===id?"bg-primary text-primary-foreground":""}`}>{PROFILES[id].label}</button>)}</div></section>
   <section className="space-y-2 border bg-card p-3"><h3 className="text-[10px] font-semibold uppercase tracking-wide">Shape</h3><N l="Rộng đáy" v={p.bottomWidth} set={n=>set("bottomWidth",n)}/><N l="Sâu đáy" v={p.bottomDepth} set={n=>set("bottomDepth",n)}/><N l="Rộng top" v={p.topWidth} set={n=>set("topWidth",n)}/><N l="Sâu top" v={p.topDepth} set={n=>set("topDepth",n)}/><N l="Chiều cao" v={p.height} set={n=>set("height",n)}/><N l="Dày thành" v={p.wallThickness} step={.05} set={n=>set("wallThickness",n)}/><N l="Dày nóc" v={p.topThickness} step={.05} set={n=>set("topThickness",n)}/><N l="Dish depth" v={p.dishDepth} step={.05} min={0} set={n=>set("dishDepth",Math.max(0,n))}/><N l="Top tilt" v={p.topTilt} step={.5} set={n=>set("topTilt",n)}/><N l="Fillet top" v={p.filletTop} step={.05} set={n=>set("filletTop",n)}/></section>
   <section className="space-y-2 border bg-card p-3"><div className="flex items-center justify-between"><h3 className="text-[10px] font-semibold uppercase tracking-wide">Stem</h3><input type="checkbox" checked={p.stemEnabled} onChange={e=>set("stemEnabled",e.target.checked)}/></div><N l="Stem Ø" v={p.stemDiameter} step={.05} set={n=>set("stemDiameter",n)}/><N l="Stem cao" v={p.stemHeight} step={.05} set={n=>set("stemHeight",n)}/><N l="Cross dài" v={p.crossLength} step={.05} set={n=>set("crossLength",n)}/><N l="Cross rộng" v={p.crossWidth} step={.05} set={n=>set("crossWidth",n)}/><N l="Clearance" v={p.stemClearance} step={.01} set={n=>set("stemClearance",n)}/></section>
  </aside>
  <main className="relative min-h-0"><div className="absolute left-1/2 top-3 z-10 flex -translate-x-1/2 gap-1 border bg-card/90 p-1 shadow-sm">{([['translate','W · Move'],['rotate','E · Rotate'],['scale','R · Scale']] as [Mode,string][]).map(([m,l])=><button key={m} onClick={()=>setMode(m)} className={`px-3 py-1.5 text-[9px] ${mode===m?"bg-primary text-primary-foreground":""}`}>{l}</button>)}</div><Scene objects={objects} state={state} selected={selected} setSelected={setSelected} mode={mode} patch={patch} p={p}/></main>
  <aside className="space-y-3 overflow-y-auto border-l p-3 pt-3">
   <section className="border bg-card p-3"><div className="mb-2 flex items-center justify-between"><div><h3 className="text-[10px] font-semibold uppercase tracking-wide">Legends</h3><p className="text-[9px] text-muted-foreground">Tối đa 8 object chữ</p></div><button onClick={addLegend} disabled={legends.length>=8} className="grid size-8 place-items-center border disabled:opacity-40"><Plus className="size-4"/></button></div><div className="space-y-1">{legends.map((l,i)=><div key={l.id} onClick={()=>setSelected(l.id)} className={`grid cursor-pointer grid-cols-[1fr_28px_28px] items-center border px-2 py-1 ${selected===l.id?"border-primary bg-primary/5":""}`}><div className="min-w-0"><div className="truncate text-[10px] font-medium">{i+1}. {l.text.replace(/\n/g," ↵ ")||"(trống)"}</div><div className="text-[9px] text-muted-foreground">{FONT_MAP[l.fontId]?.name} · {l.size} mm</div></div><button onClick={e=>{e.stopPropagation();duplicateLegend(l.id)}} className="grid size-7 place-items-center"><Copy className="size-3"/></button><button disabled={legends.length<=1} onClick={e=>{e.stopPropagation();removeLegend(l.id)}} className="grid size-7 place-items-center disabled:opacity-30"><Trash2 className="size-3"/></button></div>)}</div></section>
   {activeLegend&&<><section className="space-y-2 border bg-card p-3"><h3 className="text-[10px] font-semibold uppercase tracking-wide">Text Designer</h3><textarea value={activeLegend.text} maxLength={80} rows={2} onChange={e=>updateLegend(activeLegend.id,{text:e.target.value})} placeholder="A / ESC / ENTER..." className="w-full resize-none border bg-background p-2 text-sm"/><div className="grid grid-cols-2 gap-2"><label className="text-[9px]">Fit<select value={activeLegend.fit} onChange={e=>updateLegend(activeLegend.id,{fit:e.target.value as FitMode})} className="mt-1 h-8 w-full border bg-background px-2"><option value="none">None</option><option value="width">Fit width</option><option value="box">Fit safe area</option></select></label><label className="text-[9px]">Căn ngang<select value={activeLegend.align} onChange={e=>updateLegend(activeLegend.id,{align:e.target.value as Align})} className="mt-1 h-8 w-full border bg-background px-2"><option value="left">Trái</option><option value="center">Giữa</option><option value="right">Phải</option></select></label></div><N l="Cỡ chữ" v={activeLegend.size} step={.1} min={.5} set={n=>updateLegend(activeLegend.id,{size:Math.max(.5,n)})}/><N l="Độ nổi" v={activeLegend.depth} step={.05} min={.05} set={n=>updateLegend(activeLegend.id,{depth:Math.max(.05,n)})}/><N l="Letter spacing" v={activeLegend.letterSpacing} step={.05} set={n=>updateLegend(activeLegend.id,{letterSpacing:n})}/><N l="Line height" v={activeLegend.lineHeight} step={.05} min={.5} set={n=>updateLegend(activeLegend.id,{lineHeight:Math.max(.5,n)})}/><N l="Z lift" v={activeLegend.zLift} step={.05} set={n=>updateLegend(activeLegend.id,{zLift:n})}/><label className="flex items-center gap-2 text-[10px]"><input type="checkbox" checked={activeLegend.bevel} onChange={e=>updateLegend(activeLegend.id,{bevel:e.target.checked})}/>Bevel chữ</label>{activeLegend.bevel&&<><N l="Bevel size" v={activeLegend.bevelSize} step={.01} set={n=>updateLegend(activeLegend.id,{bevelSize:Math.max(0,n)})}/><N l="Bevel thickness" v={activeLegend.bevelThickness} step={.01} set={n=>updateLegend(activeLegend.id,{bevelThickness:Math.max(0,n)})}/></>}<div><div className="mb-1 text-[9px] uppercase tracking-wide text-muted-foreground">Vị trí nhanh</div><div className="grid grid-cols-3 gap-1">{(["tl","tc","tr","ml","mc","mr","bl","bc","br"] as Placement[]).map((pl,i)=><button key={pl} onClick={()=>applyPlacement(activeLegend.id,pl)} className={`h-7 border text-[9px] ${activeLegend.placement===pl?"bg-primary text-primary-foreground":""}`}>{["↖","↑","↗","←","●","→","↙","↓","↘"][i]}</button>)}</div></div></section>
   <section className="border bg-card p-3"><div className="mb-2 flex items-center gap-2"><Search className="size-3.5 text-muted-foreground"/><input value={fontQuery} onChange={e=>setFontQuery(e.target.value)} placeholder="Tìm font..." className="h-8 flex-1 border bg-background px-2 text-[10px]"/></div><div className="mb-2 flex gap-1 overflow-x-auto">{(["all","serif","sans","display","mono"] as FontCategory[]).map(c=><button key={c} onClick={()=>setFontCat(c)} className={`border px-2 py-1 text-[9px] capitalize ${fontCat===c?"bg-primary text-primary-foreground":""}`}>{c}</button>)}</div><div className="max-h-56 space-y-1 overflow-y-auto">{filteredFonts.map(f=><button key={f.id} onClick={()=>updateLegend(activeLegend.id,{fontId:f.id})} className={`grid w-full grid-cols-[46px_1fr_auto] items-center border px-2 py-2 text-left ${activeLegend.fontId===f.id?"border-primary bg-primary/5":""}`}><span className="text-center text-[24px] leading-none" style={{fontFamily:f.preview,fontWeight:f.id.includes("bold")?800:500}}>A</span><span><span className="block text-[10px] font-medium">{f.name}</span><span className="block text-[8px] uppercase text-muted-foreground">{f.category}</span></span><span className="text-[8px] text-emerald-600">FDM</span></button>)}</div>{fontError&&<p className="mt-2 text-[9px] text-red-600">{fontError}</p>}</section></>}
   <section className="border bg-card p-3"><h3 className="mb-2 text-[10px] font-semibold uppercase tracking-wide">Objects</h3><div className="space-y-1">{ids.map(id=><div key={id} onClick={()=>setSelected(id)} className={`grid cursor-pointer grid-cols-[28px_28px_1fr_28px] items-center gap-1 border p-1 ${selected===id?"border-primary bg-primary/5":""}`}><button onClick={e=>{e.stopPropagation();patch(id,{visible:!state[id]?.visible})}} className="grid size-7 place-items-center">{state[id]?.visible?<Eye className="size-3.5"/>:<EyeOff className="size-3.5"/>}</button><input type="color" value={state[id]?.color||"#ffffff"} onClick={e=>e.stopPropagation()} onChange={e=>patch(id,{color:e.target.value})} className="size-6"/><span className="truncate text-[9px]">{labelOf(id,legends)}</span><button onClick={e=>{e.stopPropagation();patch(id,{locked:!state[id]?.locked})}} className="grid size-7 place-items-center">{state[id]?.locked?<Lock className="size-3.5"/>:<Unlock className="size-3.5"/>}</button></div>)}</div></section>
   {state[selected]&&<section className="space-y-2 border bg-card p-3"><h3 className="text-[10px] font-semibold uppercase tracking-wide">Inspector · {labelOf(selected,legends)}</h3><V title="Position" v={state[selected].position} set={v=>patch(selected,{position:v})}/><V title="Rotation" v={state[selected].rotation} set={v=>patch(selected,{rotation:v})}/><V title="Scale" v={state[selected].scale} set={v=>patch(selected,{scale:v})}/><button onClick={()=>resetObject(selected)} className="flex h-8 w-full items-center justify-center gap-1 border text-[9px]"><RotateCcw className="size-3"/>Reset object</button></section>}
   <section className="sticky bottom-0 border bg-card p-3 shadow-[0_-6px_20px_rgba(15,23,42,.06)]"><div className="mb-2 grid grid-cols-4 gap-1">{(["combined","body","stem","legends"] as ExportMode[]).map(x=><button key={x} onClick={()=>setExportMode(x)} className={`border px-1 py-1 text-[8px] uppercase ${exportMode===x?"bg-primary text-primary-foreground":""}`}>{x}</button>)}</div><button onClick={()=>exportByMode(exportMode,objects,state)} className="flex h-9 w-full items-center justify-center gap-2 bg-primary text-[10px] font-medium text-primary-foreground"><Download className="size-4"/>Export {exportMode.toUpperCase()} STL</button></section>
  </aside>
 </div>
}
