import React, { Suspense, lazy, useEffect, useMemo, useState } from "react";
import { Box, Grid3X3, LayoutGrid, Wrench, Cuboid, CircleDot, Layers3, ScanLine } from "lucide-react";

const Keycap = lazy(() => import("./KeycapAdvancedV5.jsx"));
const Tray = lazy(() => import("./ClickerTray"));
const Layout = lazy(() => import("./Layout"));
const Editor = lazy(() => import("./Editor"));
type Tool = "keycap" | "tray" | "layout" | "editor";

type Meta = {label:string;short:string;description:string;icon:React.ComponentType<{className?:string}>};
const META:Record<Tool,Meta>={
  keycap:{label:"Keycap Designer",short:"Keycap",description:"Tạo nhiều keycap, stem, chữ và icon",icon:Box},
  tray:{label:"Clicker Holder",short:"Clicker",description:"Thiết kế khay / holder cho MX switch",icon:Grid3X3},
  layout:{label:"Layout Builder",short:"Layout",description:"Bố trí nhiều keycap và switch plate",icon:LayoutGrid},
  editor:{label:"Mesh Editor",short:"Mesh",description:"Import, tách và chỉnh sửa STL / OBJ / 3MF",icon:Wrench},
};
class Boundary extends React.Component<{children:React.ReactNode;name:string},{error:Error|null}>{state={error:null as Error|null};static getDerivedStateFromError(error:Error){return{error}}componentDidUpdate(prev:{children:React.ReactNode;name:string}){if(prev.name!==this.props.name&&this.state.error)this.setState({error:null})}render(){if(this.state.error)return <div className="grid h-full place-items-center bg-background p-6"><div className="max-w-lg border bg-card p-6 text-center shadow-sm"><h2 className="text-base font-semibold">Module {this.props.name} gặp lỗi</h2><pre className="mt-3 overflow-auto border bg-muted p-2 text-left text-[10px]">{this.state.error.message}</pre></div></div>;return this.props.children}}
function fromHash():Tool{const h=location.hash.replace("#","");return h==="tray"||h==="layout"||h==="editor"?h:"keycap"}
export default function Studio(){const[tool,setTool]=useState<Tool>(()=>fromHash());useEffect(()=>{const f=()=>setTool(fromHash());addEventListener("hashchange",f);return()=>removeEventListener("hashchange",f)},[]);const go=(t:Tool)=>{location.hash=t;setTool(t)};const meta=useMemo(()=>META[tool],[tool]);return <div className="studio-shell h-screen overflow-hidden bg-background text-foreground"><header className="studio-topbar"><div className="flex min-w-0 items-center gap-3"><div className="brand-mark"><Cuboid className="size-4"/></div><div className="min-w-0"><div className="flex items-center gap-2"><span className="brand-name">KEYCAP STUDIO</span><span className="build-badge">V5</span></div><div className="truncate text-[10px] text-muted-foreground">Parametric keycap & MX switch workspace</div></div></div><div className="topbar-context"><span className="context-kicker">WORKSPACE</span><span className="context-title">{meta.label}</span><span className="context-separator"/><span className="context-description">{meta.description}</span></div><div className="flex items-center gap-2 text-[10px] text-muted-foreground"><span className="status-chip"><CircleDot className="size-3 text-emerald-600"/>WebGL</span><span className="status-chip"><ScanLine className="size-3"/>Z-up</span><span className="unit-chip">mm</span></div></header><aside className="studio-rail"><div className="rail-tools">{(Object.keys(META) as Tool[]).map(id=>{const m=META[id],Icon=m.icon;return <button key={id} onClick={()=>go(id)} className={`rail-tool ${tool===id?"is-active":""}`}><Icon className="size-[18px]"/><span>{m.short}</span></button>})}</div><div className="rail-footer"><Layers3 className="size-4"/><span>3D</span></div></aside><main className="studio-workspace"><Boundary name={tool}><Suspense fallback={<div className="grid h-full place-items-center">Đang tải…</div>}>{tool==="keycap"?<Keycap/>:tool==="tray"?<Tray/>:tool==="layout"?<Layout/>:<Editor/>}</Suspense></Boundary></main></div>}
